// preempt_asm_arm64 — the asyncPreempt trampoline. **Not yet
// implemented; this is milestone M8.**
//
// Every part of the amd64 body is x86-shaped in a way that has an arm64
// answer, but not a mechanical one:
//
//   * The GPR save/restore is `push`/`pop`; arm64 wants paired
//     `stp`/`ldp` against an explicitly-managed SP.
//   * Flags are saved with `pushfq`/`popfq`; arm64 needs NZCV and FPSR
//     read out with `mrs` and written back with `msr`.
//   * The 128-byte red-zone skip has nothing to correspond to — AAPCS64
//     has no red zone.
//   * FP state is `fxsave64`; arm64 must save v0–v31 explicitly.
//   * **`x18` must be excluded.** `runtime/mkpreempt.go:573` skips it
//     outright — "R18 is not used, skip" — because it is the platform
//     register and touching it is a bug on every OS that reserves it.
//
// `ASYNC_PREEMPT_STACK` also has to be re-derived: the amd64 value
// budgets for a different register file and a red zone that does not
// exist here.
//
// Go: `runtime/preempt_arm64.s` (generated by `runtime/mkpreempt.go`).

/// See `preempt_asm_amd64::goish_async_preempt`. M8.
///
/// Reached only if the SIGURG preempt handler is armed on arm64, which
/// `preempt::install()` does not do before M8 — and the staged
/// `__goish_rt0` boot path does not call `install()` at all.
pub unsafe extern "C" fn goish_async_preempt() {
    let msg = b"goish: arm64 async preemption is not implemented yet (M8)\n";
    crate::syscall::Write(crate::syscall::STDERR, msg.as_ptr(), msg.len());
    crate::syscall::Exit(2);
}

// End-marker for the trampoline's PC range — see the note in
// `sched/gobuf_asm_arm64.rs`. M8 replaces this with the real in-body
// label.
core::arch::global_asm!(
    ".globl goish_async_preempt_end",
    "goish_async_preempt_end:",
    "    ret",
);
