// preempt_asm_arm64 — the asyncPreempt trampoline for arm64.
//
// darwin/arm64 is implemented (M8); linux/arm64 still aborts, because
// the resume half below needs an arm64 signal-context accessor and that
// target does not arm the SIGURG handler yet.
//
// Go: `runtime/preempt_arm64.s` (generated by `runtime/mkpreempt.go`)
// and `runtime/signal_arm64.go` (`pushCall`). The save half follows
// them; the RESUME half cannot, and that is the design point of this
// file.
//
// ─── Why resume goes through a second signal ─────────────────────────
//
// amd64 ends its trampoline with `jmp qword ptr [rsp - 144]`: a branch
// through memory, taken after every register is back. arm64 has no
// memory-indirect branch — a jump needs a register — and once x0–x30
// are restored there is no register left that the interrupted code was
// not possibly using. Go's arm64 trampoline spends R27, which its ABI
// reserves (REGTMP); goish interrupts arbitrary Rust, where x16/x17 are
// ordinary allocatable registers and x18 is Apple's platform register.
//
// So the trampoline never restores. It saves every register the
// interrupted code could be using, calls `goish_async_preempt2` (which
// yields; the G may come back on another M), and then executes `brk`.
// The SIGTRAP that raises is synchronous, on whichever thread now runs
// the G; its handler (`preempt::goish_preempt_restore`) recognises the
// one `brk` address, copies the saved registers — GPRs, lr, sp, pc,
// NZCV, q0–q31, FPSR, FPCR — into the signal context, and returns. The
// kernel's sigreturn then restores all of them at once, exactly.
//
// Cost: one extra signal per *forced* preemption (sysmon issues those
// only for a G that has run 10 ms without yielding). A debugger that
// intercepts EXC_BREAKPOINT will stop at that `brk`; tell it to pass
// SIGTRAP through.
//
// ─── Frame (built by the SIGURG handler, then by this trampoline) ───
//
//   S+16  resume pc  (the interrupted PC)       ┐ written by the handler,
//   S+8   original sp                            │ below the 128-byte red
//   S+0   original lr                            ┘ zone Apple's ABI keeps
//   S-768 save area: x0..x28 at 0..232, x29 at 232, NZCV at 240,
//         FPSR/FPCR at 248/252, q0..q31 at 256..768
//   S-784 frame record {x29, resume pc} for unwinders → x29
//
// x18 is stored with its neighbour for alignment and never restored.

/// Size of the register save area, shared with the SIGTRAP restorer.
#[cfg(target_os = "macos")]
pub(crate) const SAVE_AREA: usize = 768;

#[cfg(target_os = "macos")]
#[unsafe(naked)]
#[no_mangle]
pub unsafe extern "C" fn goish_async_preempt() {
    core::arch::naked_asm!(
        "sub sp, sp, #768",
        "stp x0, x1, [sp, #0]",
        "stp x2, x3, [sp, #16]",
        "stp x4, x5, [sp, #32]",
        "stp x6, x7, [sp, #48]",
        "stp x8, x9, [sp, #64]",
        "stp x10, x11, [sp, #80]",
        "stp x12, x13, [sp, #96]",
        "stp x14, x15, [sp, #112]",
        "stp x16, x17, [sp, #128]",
        "stp x18, x19, [sp, #144]",
        "stp x20, x21, [sp, #160]",
        "stp x22, x23, [sp, #176]",
        "stp x24, x25, [sp, #192]",
        "stp x26, x27, [sp, #208]",
        "str x28, [sp, #224]",
        "str x29, [sp, #232]",
        "mrs x0, nzcv",
        "str x0, [sp, #240]",
        "mrs x0, fpsr",
        "mrs x1, fpcr",
        "stp w0, w1, [sp, #248]",
        "stp q0, q1, [sp, #256]",
        "stp q2, q3, [sp, #288]",
        "stp q4, q5, [sp, #320]",
        "stp q6, q7, [sp, #352]",
        "stp q8, q9, [sp, #384]",
        "stp q10, q11, [sp, #416]",
        "stp q12, q13, [sp, #448]",
        "stp q14, q15, [sp, #480]",
        "stp q16, q17, [sp, #512]",
        "stp q18, q19, [sp, #544]",
        "stp q20, q21, [sp, #576]",
        "stp q22, q23, [sp, #608]",
        "stp q24, q25, [sp, #640]",
        "stp q26, q27, [sp, #672]",
        "stp q28, q29, [sp, #704]",
        "stp q30, q31, [sp, #736]",
        // A frame record naming the interrupted PC as our caller, so a
        // stack walk from inside the yield reads like a call from there.
        "ldr x30, [sp, #784]",
        "stp x29, x30, [sp, #-16]!",
        "mov x29, sp",
        "bl {async_preempt2}",
        // Resumed. Everything is restored by the SIGTRAP handler.
        ".globl _goish_async_preempt_restore",
        "_goish_async_preempt_restore:",
        "brk #0xf00d",
        ".globl _goish_async_preempt_end",
        "_goish_async_preempt_end:",
        "brk #0xf00e",
        async_preempt2 = sym super::preempt::goish_async_preempt2,
    )
}

/// linux/arm64: not implemented (see the header). Reached only if the
/// SIGURG handler were armed there, which `__goish_rt0` does not do.
#[cfg(not(target_os = "macos"))]
pub unsafe extern "C" fn goish_async_preempt() {
    let msg = b"goish: linux/arm64 async preemption is not implemented yet (M8)\n";
    crate::syscall::Write(crate::syscall::STDERR, msg.as_ptr(), msg.len());
    crate::syscall::Exit(2);
}

// End-marker for the trampoline's PC range on linux/arm64.
#[cfg(not(target_os = "macos"))]
core::arch::global_asm!(
    ".globl goish_async_preempt_end",
    "goish_async_preempt_end:",
    "    ret",
);
