// zerrors_darwin_arm64 — Darwin's constant table.
//
// Go: `syscall/zerrors_darwin_arm64.go`, generated by `mkerrors.sh` from
// the SDK headers. This file is the same thing by the same method:
// every numeric value below was read out of
// `$(xcrun --show-sdk-path)/usr/include` by compiling and running a
// program that prints them, not written from memory.
//
// **Why that matters more here than anywhere else in the port.** These
// constants are the part of the Darwin surface that rustc cannot check.
// A missing function is a compile error; a Linux number left in a
// Darwin file compiles clean and is wrong at runtime, silently. And
// they really do differ — not at the margins:
//
//   SIGURG    Linux 23  Darwin 16     SIGUSR1   Linux 10  Darwin 30
//   SIGCHLD   Linux 17  Darwin 20     SIGSTOP   Linux 19  Darwin 17
//   SIGCONT   Linux 18  Darwin 19     SIGUSR2   Linux 12  Darwin 31
//   EAGAIN    Linux 11  Darwin 35     ENOSYS    Linux 38  Darwin 78
//   ENOTEMPTY Linux 39  Darwin 66     EOPNOTSUPP Linux 95 Darwin 102
//   SA_ONSTACK 0x08000000 → 1         SA_SIGINFO 4 → 64
//   MAP_ANONYMOUS 0x20 → MAP_ANON 0x1000
//   O_CLOEXEC 0o2000000 → 0x1000000   AT_FDCWD  -100 → -2
//   SOL_SOCKET 1 → 0xffff             SO_ERROR 4 → 0x1007
//
// SIGURG is the one that would have been most expensive to find by
// hand: it is goish's async-preemption signal, so a Linux 23 here would
// have sent SIGUSR1 to every M.
//
// ─── Constants with no Darwin analogue ────────────────────────────────
//
// futex, clone, arch_prctl, epoll, eventfd, inotify, fanotify and
// `SA_RESTORER` are Linux kernel interfaces, not merely Linux spellings.
// Their names still have to resolve, because the code that uses them
// (`runtime/netpoll`, `runtime/note`, `os/inotify`) compiles on this
// target even though none of it runs yet.
//
// Every one of them is defined as `POISON` rather than as a plausible
// number. A zero or a copied-from-Linux value would flow through bit
// arithmetic and produce a wrong result somewhere far away; an all-ones
// value fails whatever it reaches, and `grep POISON` enumerates the
// entire set. The functions that would consume them are
// `unimplemented!()` in `syscall_darwin.rs`, so nothing reaches them
// today — the poison is the backstop for when M7/M9 start moving.

// ─── signals ───────────────────────────────────────────────────────────
//
// Go: `syscall/zerrors_darwin_arm64.go`; SDK `sys/signal.h`.
pub const SIGHUP: i32 = 1;
pub const SIGINT: i32 = 2;
pub const SIGQUIT: i32 = 3;
pub const SIGILL: i32 = 4;
pub const SIGTRAP: i32 = 5;
pub const SIGABRT: i32 = 6;
pub const SIGFPE: i32 = 8;
pub const SIGKILL: i32 = 9;
pub const SIGSEGV: i32 = 11;
pub const SIGPIPE: i32 = 13;
pub const SIGALRM: i32 = 14;
pub const SIGTERM: i32 = 15;
/// **16 on Darwin, 23 on Linux.** goish's async-preemption signal
/// (M8) — Go picks SIGURG for the same reason on both
/// (`runtime/signal_unix.go`, `preemptM` → `signalM(mp, sigPreempt)`).
pub const SIGURG: i32 = 16;
pub const SIGSTOP: i32 = 17;
pub const SIGTSTP: i32 = 18;
pub const SIGCONT: i32 = 19;
pub const SIGCHLD: i32 = 20;
pub const SIGTTIN: i32 = 21;
pub const SIGTTOU: i32 = 22;
pub const SIGXCPU: i32 = 24;
pub const SIGXFSZ: i32 = 25;
pub const SIGWINCH: i32 = 28;
pub const SIGUSR1: i32 = 30;
pub const SIGUSR2: i32 = 31;

// ─── sigaction flags ───────────────────────────────────────────────────
pub const SA_ONSTACK: u64 = 0x0001;
pub const SA_RESTART: u64 = 0x0002;
pub const SA_SIGINFO: u64 = 0x0040;

/// **No Darwin analogue.** `SA_RESTORER` is the amd64-Linux mechanism
/// for supplying a userspace `rt_sigreturn` trampoline; BSD `sigaction`
/// has no `sa_restorer` field at all and libSystem's own trampoline
/// returns from the handler. See `sigreturn_restorer` in
/// `syscall_darwin.rs`.
pub const SA_RESTORER: u64 = POISON_U64;

// ─── clock ids ─────────────────────────────────────────────────────────
//
// `CLOCK_MONOTONIC` is 6 here and 1 on Linux, and the difference is
// not only the number: Darwin's counts time asleep, Linux's does not.
// `CLOCK_UPTIME_RAW` (8) is the one that does not — it is
// `mach_absolute_time` *with* the timebase conversion applied, i.e. Go's
// darwin `nanotime` — and `runtime::sysmon::NANOTIME_CLOCK` selects it.
pub const CLOCK_REALTIME: i32 = 0;
pub const CLOCK_MONOTONIC: i32 = 6;
pub const CLOCK_MONOTONIC_RAW: i32 = 4;
pub const CLOCK_UPTIME_RAW: i32 = 8;

/// `utimensat` "leave this timestamp alone". Darwin spells it `-2`;
/// Linux uses the bit pattern `0x3ffffffe`.
pub const UTIME_OMIT: i64 = -2;

// ─── standard fds ──────────────────────────────────────────────────────
pub const STDIN: i32 = 0;
pub const STDOUT: i32 = 1;
pub const STDERR: i32 = 2;

// ─── mmap ──────────────────────────────────────────────────────────────
pub const PROT_NONE: i32 = 0;
pub const PROT_READ: i32 = 1;
pub const PROT_WRITE: i32 = 2;
pub const PROT_EXEC: i32 = 4;

pub const MAP_PRIVATE: i32 = 0x02;
pub const MAP_FIXED: i32 = 0x10;
/// Darwin spells it `MAP_ANON` and numbers it `0x1000`; Linux's
/// `MAP_ANONYMOUS` is `0x20`. The goish name follows Linux because
/// every caller already uses it.
pub const MAP_ANONYMOUS: i32 = 0x1000;
/// Present in the SDK (`0x40`) but documented as a no-op on Darwin —
/// there is no commit-charge accounting to opt out of. Kept so the
/// goroutine-stack reservation path compiles; M2 decides whether to
/// pass it at all.
pub const MAP_NORESERVE: i32 = 0x40;

/// `madvise(2)` advice. **`MADV_DONTNEED` exists here and does not do
/// what it does on Linux** — it does not free the pages and does not
/// zero them. Go's Darwin release path is the `MADV_FREE_REUSABLE` /
/// `MADV_FREE_REUSE` pair (`runtime/mem_darwin.go:23-34`). M2 owns the
/// choice; both are spelled out here so it is made explicitly.
pub const MADV_DONTNEED: i32 = 4;
pub const MADV_FREE: i32 = 5;
pub const MADV_FREE_REUSABLE: i32 = 7;
pub const MADV_FREE_REUSE: i32 = 8;

/// Sentinel returned by `mmap(2)` on failure (`(void *) -1`).
pub const MAP_FAILED: *mut u8 = !0usize as *mut u8;

// ─── open / fcntl ──────────────────────────────────────────────────────
pub const O_RDONLY: i32 = 0x0;
pub const O_WRONLY: i32 = 0x1;
pub const O_RDWR: i32 = 0x2;
pub const O_NONBLOCK: i32 = 0x4;
pub const O_APPEND: i32 = 0x8;
pub const O_CREAT: i32 = 0x200;
pub const O_TRUNC: i32 = 0x400;
pub const O_DIRECTORY: i32 = 0x100000;
pub const O_CLOEXEC: i32 = 0x1000000;

/// **No Darwin analogue.** Linux's `O_PATH` opens a descriptor that
/// refers to a path without granting read or write. Darwin has no
/// equivalent flag.
pub const O_PATH: i32 = POISON_I32;

pub const F_GETFD: i32 = 1;
pub const F_SETFD: i32 = 2;
pub const F_GETFL: i32 = 3;
pub const F_SETFL: i32 = 4;
pub const F_NOCACHE: i32 = 48;
/// Darwin's real "flush to platter" — plain `fsync(2)` on macOS only
/// hands the data to the drive. Go: `internal/poll/fd_fsync_darwin.go`.
pub const F_FULLFSYNC: i32 = 51;
pub const FD_CLOEXEC: i32 = 1;

/// **-2 on Darwin, -100 on Linux.**
pub const AT_FDCWD: i32 = -2;
pub const AT_REMOVEDIR: i32 = 0x80;
pub const AT_SYMLINK_NOFOLLOW: i32 = 0x20;

// ─── stat / seek / flock ───────────────────────────────────────────────
//
// The `S_IF*` values are POSIX and identical to Linux's. **The type is
// not:** Darwin's `mode_t` is 16-bit, so `struct stat`'s `st_mode` is a
// `u16` sitting at offset 4 with `st_nlink` immediately after it at
// offset 6 — there is no room to widen it. Go makes the same split
// (`syscall.Stat_t.Mode` is `uint16` on darwin, `uint32` on linux).
//
// Typing the constants to match keeps every caller portable with no
// cast: `st.st_mode & S_IFMT` is `u16 & u16` here and `u32 & u32` on
// Linux, and `(st.st_mode & 0o777) as u32` works unchanged on both.
pub const S_IFMT: u16 = 0o170000;
pub const S_IFDIR: u16 = 0o040000;
pub const S_IFREG: u16 = 0o100000;
pub const S_IFLNK: u16 = 0o120000;

pub const SEEK_SET: i32 = 0;
pub const SEEK_CUR: i32 = 1;
pub const SEEK_END: i32 = 2;

pub const LOCK_SH: i32 = 1;
pub const LOCK_EX: i32 = 2;
pub const LOCK_NB: i32 = 4;
pub const LOCK_UN: i32 = 8;

// ─── dirent types ──────────────────────────────────────────────────────
//
// Also identical — 4.4BSD's `d_type` values, which Linux adopted.
pub const DT_UNKNOWN: u8 = 0;
pub const DT_FIFO: u8 = 1;
pub const DT_CHR: u8 = 2;
pub const DT_DIR: u8 = 4;
pub const DT_BLK: u8 = 6;
pub const DT_REG: u8 = 8;
pub const DT_LNK: u8 = 10;
pub const DT_SOCK: u8 = 12;

// ─── sockets ───────────────────────────────────────────────────────────
pub const AF_UNIX: i32 = 1;
pub const AF_INET: i32 = 2;
/// 30 on Darwin, 10 on Linux.
pub const AF_INET6: i32 = 30;

pub const SOCK_STREAM: i32 = 1;
pub const SOCK_DGRAM: i32 = 2;

/// **No Darwin analogue.** Linux folds `SOCK_CLOEXEC` / `SOCK_NONBLOCK`
/// into the `type` argument of `socket(2)` and `accept4(2)`; BSD has
/// neither, and Go sets both with `fcntl` after the fact
/// (`internal/poll/sys_cloexec.go`). M9's problem.
pub const SOCK_CLOEXEC: i32 = POISON_I32;
pub const SOCK_NONBLOCK: i32 = POISON_I32;

pub const IPPROTO_TCP: i32 = 6;
pub const IPPROTO_UDP: i32 = 17;
pub const IPPROTO_IPV6: i32 = 41;

/// **0xffff on Darwin, 1 on Linux.**
pub const SOL_SOCKET: i32 = 0xffff;
pub const SO_REUSEADDR: i32 = 0x0004;
pub const SO_KEEPALIVE: i32 = 0x0008;
pub const SO_LINGER: i32 = 0x0080;
pub const SO_REUSEPORT: i32 = 0x0200;
pub const SO_SNDTIMEO: i32 = 0x1005;
pub const SO_RCVTIMEO: i32 = 0x1006;
pub const SO_ERROR: i32 = 0x1007;
pub const SO_TYPE: i32 = 0x1008;
/// Per-socket SIGPIPE suppression. Darwin-only, and the reason the
/// process-wide `SIG_IGN` in `__goish_rt0` has a cleaner answer here
/// than on Linux. Go uses it in `net/sockopt_bsd.go`.
pub const SO_NOSIGPIPE: i32 = 0x1022;

/// 27 on Darwin, 26 on Linux.
pub const IPV6_V6ONLY: i32 = 27;

pub const TCP_NODELAY: i32 = 1;
/// Darwin's `TCP_KEEPALIVE` (0x10) is the analogue of Linux's
/// `TCP_KEEPIDLE` (4) — same role, different name and number. Go maps
/// them in `net/tcpsockopt_darwin.go`.
pub const TCP_KEEPIDLE: i32 = 0x10;
pub const TCP_KEEPINTVL: i32 = 0x101;
pub const TCP_KEEPCNT: i32 = 0x102;

pub const SHUT_RD: i32 = 0;
pub const SHUT_WR: i32 = 1;
pub const SHUT_RDWR: i32 = 2;

pub const INADDR_ANY: u32 = 0;

pub const MSG_PEEK: i32 = 0x2;
/// 0x80 on Darwin, 0x40 on Linux.
pub const MSG_DONTWAIT: i32 = 0x80;

// ─── termios ───────────────────────────────────────────────────────────
//
// The `ioctl` request numbers are BSD `_IOR`/`_IOW` encodings and share
// nothing with Linux's small integers. The goish names keep the Linux
// spelling; the values are Darwin's `TIOCGETA` / `TIOCSETA`.
pub const TCGETS: usize = 0x40487413;
pub const TCSETS: usize = 0x80487414;
pub const TIOCGWINSZ: usize = 0x40087468;
pub const TIOCSWINSZ: usize = 0x80087467;
/// Darwin's `TIOCPTYGNAME` returns the *name* of the pty, where Linux's
/// `TIOCGPTN` returns its number — same purpose, incompatible result,
/// so the pty code needs more than a renumber. Not M1's problem.
pub const TIOCGPTN: usize = 0x40807453;
/// Darwin's `TIOCPTYUNLK`. Linux's `TIOCSPTLCK` takes a pointer to an
/// int; this one takes no argument.
pub const TIOCSPTLCK: usize = 0x20007452;

// c_iflag / c_oflag / c_cflag / c_lflag bits.
//
// **Typed `u64`, not `u32`.** Darwin's `tcflag_t` is `unsigned long`,
// so `struct termios` is four 8-byte flag words where Linux has four
// 4-byte ones (measured: `c_ispeed` sits at offset 56 here, 20 there).
// The bit values below are POSIX for the low `c_iflag` bits and diverge
// from Linux everywhere else.
pub const IGNBRK: u64 = 0x1;
pub const BRKINT: u64 = 0x2;
pub const PARMRK: u64 = 0x8;
pub const ISTRIP: u64 = 0x20;
pub const INLCR: u64 = 0x40;
pub const IGNCR: u64 = 0x80;
pub const ICRNL: u64 = 0x100;
/// 0x200 on Darwin, 0x400 on Linux — the first `c_iflag` bit to diverge.
pub const IXON: u64 = 0x200;

pub const OPOST: u64 = 0x1;

// c_cflag — 0x300 here against Linux's 0x30.
pub const CSIZE: u64 = 0x300;
pub const CS8: u64 = 0x300;
pub const PARENB: u64 = 0x1000;

// c_lflag — every one of these differs from Linux.
pub const ECHO: u64 = 0x8;
pub const ECHONL: u64 = 0x10;
pub const ISIG: u64 = 0x80;
pub const ICANON: u64 = 0x100;
pub const IEXTEN: u64 = 0x400;

// c_cc indices — 16/17 here, 6/5 on Linux, and swapped in order.
pub const VMIN: usize = 16;
pub const VTIME: usize = 17;

// ─── poll ──────────────────────────────────────────────────────────────
pub const POLLIN: i16 = 0x1;
pub const POLLERR: i16 = 0x8;
pub const POLLHUP: i16 = 0x10;
pub const POLLNVAL: i16 = 0x20;

// ─── Linux-only interfaces ─────────────────────────────────────────────
//
// See the header. Names resolve; values are poison; the functions that
// consume them are `unimplemented!()`.

/// Poison for a Linux-only constant with no Darwin analogue. All-ones
/// so it fails whatever it reaches instead of looking plausible.
const POISON_I32: i32 = -1;
const POISON_U32: u32 = !0;
const POISON_U64: u64 = !0;

// futex(2) — Darwin's replacement is `pthread_cond_timedwait_relative_np`
// (Go: `runtime/os_darwin.go:36-71`, `semacreate`/`semasleep`). M7.
pub const FUTEX_PRIVATE_FLAG: i32 = POISON_I32;
pub const FUTEX_WAIT_PRIVATE: i32 = POISON_I32;
pub const FUTEX_WAKE_PRIVATE: i32 = POISON_I32;

// arch_prctl(2) — x86-Linux only; unreachable on any arm64 target.
pub const ARCH_SET_FS: i32 = POISON_I32;
pub const ARCH_GET_FS: i32 = POISON_I32;

// clone(2) — Darwin creates threads with `pthread_create`
// (Go: `runtime/os_darwin.go:233-258`). M4.
pub const CLONE_VM: u64 = POISON_U64;
pub const CLONE_FS: u64 = POISON_U64;
pub const CLONE_FILES: u64 = POISON_U64;
pub const CLONE_SIGHAND: u64 = POISON_U64;
pub const CLONE_THREAD: u64 = POISON_U64;
pub const CLONE_SYSVSEM: u64 = POISON_U64;
pub const CLONE_SETTLS: u64 = POISON_U64;
pub const CLONE_THREAD_FLAGS: u64 = POISON_U64;

// epoll — Darwin's netpoller is kqueue, with `EVFILT_USER` +
// `NOTE_TRIGGER` for the wake (Go: `runtime/netpoll_kqueue_event.go`).
// M9.
pub const EPOLL_CTL_ADD: i32 = POISON_I32;
pub const EPOLL_CTL_DEL: i32 = POISON_I32;
pub const EPOLL_CTL_MOD: i32 = POISON_I32;
pub const EPOLLIN: u32 = POISON_U32;
pub const EPOLLOUT: u32 = POISON_U32;
pub const EPOLLERR: u32 = POISON_U32;
pub const EPOLLHUP: u32 = POISON_U32;
pub const EPOLLRDHUP: u32 = POISON_U32;
pub const EPOLLET: u32 = POISON_U32;
pub const EPOLLONESHOT: u32 = POISON_U32;

// eventfd(2) — no analogue; the kqueue wake replaces its role.
pub const EFD_CLOEXEC: i32 = POISON_I32;
pub const EFD_NONBLOCK: i32 = POISON_I32;

// getrandom(2) flags — Darwin's entropy source is `arc4random_buf`,
// which is infallible and takes no flags (Go: `runtime/os_darwin.go`,
// `readRandom`). M3.
pub const GRND_NONBLOCK: u32 = POISON_U32;
pub const GRND_RANDOM: u32 = POISON_U32;
pub const GRND_INSECURE: u32 = POISON_U32;

// inotify(7) — Darwin's file-change interface is kqueue `EVFILT_VNODE`
// or FSEvents; neither is a renumber of this.
pub const IN_CLOEXEC: i32 = POISON_I32;
pub const IN_NONBLOCK: i32 = POISON_I32;
pub const IN_MODIFY: u32 = POISON_U32;
pub const IN_MOVED_FROM: u32 = POISON_U32;
pub const IN_MOVED_TO: u32 = POISON_U32;
pub const IN_CREATE: u32 = POISON_U32;
pub const IN_DELETE: u32 = POISON_U32;
pub const IN_DELETE_SELF: u32 = POISON_U32;
pub const IN_MOVE_SELF: u32 = POISON_U32;
pub const IN_Q_OVERFLOW: u32 = POISON_U32;
pub const IN_ONLYDIR: u32 = POISON_U32;
pub const IN_DONT_FOLLOW: u32 = POISON_U32;
pub const IN_EXCL_UNLINK: u32 = POISON_U32;
pub const IN_ISDIR: u32 = POISON_U32;
#[allow(non_upper_case_globals)]
pub const SizeofInotifyEvent: usize = 0x10;

// fanotify(7) — Linux-only in the strongest sense: there is no BSD
// interface with this shape at all.
pub const FAN_CLASS_NOTIF: u32 = POISON_U32;
pub const FAN_CLOEXEC: u32 = POISON_U32;
pub const FAN_NONBLOCK: u32 = POISON_U32;
pub const FAN_REPORT_FID: u32 = POISON_U32;
pub const FAN_REPORT_DIR_FID: u32 = POISON_U32;
pub const FAN_REPORT_NAME: u32 = POISON_U32;
pub const FAN_REPORT_DFID_NAME: u32 = POISON_U32;
pub const FAN_MODIFY: u64 = POISON_U64;
pub const FAN_MOVED_FROM: u64 = POISON_U64;
pub const FAN_MOVED_TO: u64 = POISON_U64;
pub const FAN_CREATE: u64 = POISON_U64;
pub const FAN_DELETE: u64 = POISON_U64;
pub const FAN_DELETE_SELF: u64 = POISON_U64;
pub const FAN_MOVE_SELF: u64 = POISON_U64;
pub const FAN_Q_OVERFLOW: u64 = POISON_U64;
pub const FAN_EVENT_ON_CHILD: u64 = POISON_U64;
pub const FAN_RENAME: u64 = POISON_U64;
pub const FAN_ONDIR: u64 = POISON_U64;
pub const FAN_MARK_ADD: u32 = POISON_U32;
pub const FAN_MARK_REMOVE: u32 = POISON_U32;
pub const FAN_MARK_DONT_FOLLOW: u32 = POISON_U32;
pub const FAN_MARK_ONLYDIR: u32 = POISON_U32;
pub const FAN_EVENT_INFO_TYPE_FID: u8 = 0x1;
pub const FAN_EVENT_INFO_TYPE_DFID_NAME: u8 = 0x2;
pub const FAN_EVENT_INFO_TYPE_DFID: u8 = 0x3;
pub const FAN_EVENT_INFO_TYPE_OLD_DFID_NAME: u8 = 0xa;
pub const FAN_EVENT_INFO_TYPE_NEW_DFID_NAME: u8 = 0xc;
pub const FANOTIFY_METADATA_VERSION: u8 = 0x3;

// ─── Errno ─────────────────────────────────────────────────────────────
//
// The type and its impls are the same on every target — only the
// numbers below it are Darwin's. Duplicated here rather than shared
// because Go duplicates it too: `syscall.Errno` is declared per-OS in
// `syscall_unix.go`'s siblings, and a shared module would need the
// table it dispatches on to be per-OS anyway.

#[derive(Copy, Clone, PartialEq, Eq, Hash, Debug, Default)]
#[allow(non_camel_case_types)]
pub struct Errno(pub i32);

impl Errno {
    /// `(e Errno) Error() string` — Darwin errno → human name. Same
    /// short table as the Linux side, **keyed by Darwin's numbers**:
    /// 66 is `ENOTEMPTY` here and `ENOTEMPTY` is 39 there, so sharing
    /// the match arms would have printed the wrong string for every
    /// value above 34.
    #[allow(non_snake_case)]
    pub fn Error(&self) -> crate::gostring::string {
        crate::gostring::string::from_static(match self.0 {
            1 => "operation not permitted",
            2 => "no such file or directory",
            4 => "interrupted system call",
            13 => "permission denied",
            17 => "file exists",
            20 => "not a directory",
            21 => "is a directory",
            35 => "resource temporarily unavailable",
            45 => "operation not supported",
            66 => "directory not empty",
            78 => "function not implemented",
            102 => "operation not supported on socket",
            _ => "errno",
        })
    }

    // go: sdk 1.25.5 syscall/syscall_unix.go:138-140 Errno.Timeout
    /// Go: `func (e Errno) Timeout() bool`. Without an inherent method
    /// here, `os`'s `syscall::Errno::Timeout(self)` resolved to the
    /// trait method it is implementing and recursed forever.
    #[allow(non_snake_case)]
    pub fn Timeout(&self) -> bool {
        *self == EAGAIN || *self == EWOULDBLOCK || *self == ETIMEDOUT
    }

    // go: sdk 1.25.5 syscall/syscall_unix.go:134-136 Errno.Temporary
    /// Go: `func (e Errno) Temporary() bool`.
    #[allow(non_snake_case)]
    pub fn Temporary(&self) -> bool {
        *self == EINTR || *self == EMFILE || *self == ENFILE || self.Timeout()
    }

    /// `Is(target)` — value equality, as on Linux.
    #[allow(non_snake_case)]
    pub fn Is(&self, target: Errno) -> bool {
        *self == target
    }
}

impl crate::errors::ErrorTrait for Errno {
    fn Error(&self) -> crate::gostring::string {
        Self::Error(self)
    }
}

impl PartialEq<i32> for Errno {
    fn eq(&self, other: &i32) -> bool {
        self.0 == *other
    }
}
impl PartialEq<Errno> for i32 {
    fn eq(&self, other: &Errno) -> bool {
        *self == other.0
    }
}
impl PartialEq<Errno> for crate::errors::error {
    fn eq(&self, other: &Errno) -> bool {
        let (e, ok) = self.As::<Errno>();
        ok && *e == *other
    }
}
impl PartialEq<crate::errors::error> for Errno {
    fn eq(&self, other: &crate::errors::error) -> bool {
        other == self
    }
}

/// Common errno values, from the SDK's `<sys/errno.h>`. Six of the ten
/// the Linux side declares have different numbers here.
pub const EPERM: Errno = Errno(1);
pub const ENOENT: Errno = Errno(2);
pub const EINTR: Errno = Errno(4);
pub const EBADF: Errno = Errno(9);
pub const ENOMEM: Errno = Errno(12);
pub const EACCES: Errno = Errno(13);
pub const EFAULT: Errno = Errno(14);
pub const EEXIST: Errno = Errno(17);
pub const ENOTDIR: Errno = Errno(20);
pub const EISDIR: Errno = Errno(21);
pub const EINVAL: Errno = Errno(22);
pub const ENFILE: Errno = Errno(23);
pub const EMFILE: Errno = Errno(24);
pub const EPIPE: Errno = Errno(32);
pub const ERANGE: Errno = Errno(34);
/// **35 here, 11 on Linux** — the divergence the plan singled out.
pub const EAGAIN: Errno = Errno(35);
/// Same value as `EAGAIN` on Darwin, as on Linux.
pub const EWOULDBLOCK: Errno = Errno(35);
pub const ETIMEDOUT: Errno = Errno(60);
pub const EINPROGRESS: Errno = Errno(36);
pub const ENOTSUP: Errno = Errno(45);
pub const ECONNABORTED: Errno = Errno(53);
pub const ECONNRESET: Errno = Errno(54);
pub const ENOBUFS: Errno = Errno(55);
pub const ENOTEMPTY: Errno = Errno(66);
pub const ENOSYS: Errno = Errno(78);
pub const EOPNOTSUPP: Errno = Errno(102);

// ─── added with upstream's os.Root, mode-bit and pprof surface ─────────
//
// Read from the SDK the same way as the rest of this file (a C program
// printing the macros against `$(xcrun --show-sdk-path)`), on rebasing
// the port onto a main that had grown these names on Linux.
//
// The mode bits are `u16` like the other `S_IF*` here — `mode_t` is
// 16-bit on Darwin and these are compared against `st_mode`. The `_M`
// spellings are Linux's names for the fifo/socket kinds as mode values.
pub const O_NOFOLLOW: i32 = 0x100;
pub const S_IFBLK: u16 = 0o060000;
pub const S_IFCHR: u16 = 0o020000;
pub const S_IFIFO_M: u16 = 0o010000;
pub const S_IFSOCK_M: u16 = 0o140000;
pub const S_ISUID: u16 = 0o4000;
pub const S_ISGID: u16 = 0o2000;
pub const S_ISVTX: u16 = 0o1000;
pub const ITIMER_PROF: i32 = 2;
pub const SIGPROF: i32 = 27;
