// ztypes_darwin_arm64 — Darwin's kernel struct layouts.
//
// Go: `syscall/ztypes_darwin_arm64.go`, generated by `cgo -godefs`. Same
// method here: every offset and size below was measured by compiling a
// program against the SDK headers and printing `offsetof`/`sizeof`, not
// transcribed.
//
// **The layouts are not Linux's with fields renamed.** `struct stat` is
// 144 bytes here against Linux's 144 with a completely different field
// order (`st_mode` is a 16-bit field at offset 4, not a 32-bit one at
// 24); `struct termios` is 72 bytes of 8-byte flag words against
// Linux's 60 with 4-byte ones; `struct sockaddr_in` leads with a
// one-byte `sin_len` that Linux does not have; `struct sigaction` has
// no `sa_restorer` at all.
//
// Where a struct is Linux-only in kind rather than in layout — the
// epoll, inotify and fanotify records — it is declared with its Linux
// shape and a note. Nothing on this target produces one; they exist so
// the modules that name them compile.

/// `struct timespec`. The one layout that is genuinely identical on
/// both targets: two 64-bit words, seconds then nanoseconds.
#[repr(C)]
#[derive(Clone, Copy, Default)]
pub struct Timespec {
    pub tv_sec: i64,
    pub tv_nsec: i64,
}

/// `struct termios` — 72 bytes.
///
/// `tcflag_t` is `unsigned long` on Darwin, so all four flag words are
/// 64-bit; Linux's are 32-bit and its struct carries a `c_line` byte
/// that BSD has no equivalent for. `NCCS` is 20 here against Linux's
/// 32, which still leaves room for `VMIN` (16) and `VTIME` (17).
#[repr(C)]
#[derive(Clone, Copy, Default)]
#[allow(non_snake_case)]
pub struct Termios {
    pub Iflag: u64,
    pub Oflag: u64,
    pub Cflag: u64,
    pub Lflag: u64,
    pub Cc: [u8; 20],
    pub Pad_cgo_0: [u8; 4],
    pub Ispeed: u64,
    pub Ospeed: u64,
}

/// `struct winsize` — identical on both targets.
#[repr(C)]
#[derive(Clone, Copy, Default)]
#[allow(non_snake_case)]
pub struct Winsize {
    pub Row: u16,
    pub Col: u16,
    pub Xpixel: u16,
    pub Ypixel: u16,
}

/// `struct stat` — 144 bytes, `_DARWIN_FEATURE_64_BIT_INODE` layout
/// (the only one arm64 has; the 32-bit-inode variant predates the
/// architecture).
///
/// Two shape differences that reach callers, both handled without
/// touching the callers:
///
///   * `st_mode` is `u16`, not `u32`. See the note on `S_IFMT` in
///     `zerrors_darwin_arm64.rs` — the constants are typed to match, so
///     `st.st_mode & S_IFMT` compiles on both targets.
///   * The timestamps are `struct timespec` rather than Linux's
///     split `st_Xtime` / `st_Xtime_nsec` pair. Since a `timespec` *is*
///     `{ i64, i64 }`, spelling the two halves out under the Linux
///     field names is layout-exact and keeps
///     `crate::time::Unix(st.st_mtime, st.st_mtime_nsec as int)`
///     working verbatim.
#[repr(C)]
#[derive(Clone, Copy, Default)]
#[allow(non_camel_case_types)]
pub struct Stat_t {
    pub st_dev: i32,
    pub st_mode: u16,
    pub st_nlink: u16,
    pub st_ino: u64,
    pub st_uid: u32,
    pub st_gid: u32,
    pub st_rdev: i32,
    pub __pad0: i32,
    pub st_atime: i64,
    pub st_atime_nsec: i64,
    pub st_mtime: i64,
    pub st_mtime_nsec: i64,
    pub st_ctime: i64,
    pub st_ctime_nsec: i64,
    /// `st_birthtimespec` — file creation time. No Linux `struct stat`
    /// field corresponds; `statx(2)` is where Linux exposes it.
    pub st_birthtime: i64,
    pub st_birthtime_nsec: i64,
    pub st_size: i64,
    pub st_blocks: i64,
    pub st_blksize: i32,
    pub st_flags: u32,
    pub st_gen: u32,
    pub st_lspare: i32,
    pub st_qspare: [i64; 2],
}

/// `struct utsname` — five 256-byte fields, 1280 bytes total.
///
/// Linux's is six 65-byte fields (390 bytes) and includes a
/// `domainname` that POSIX does not define and Darwin does not have.
#[repr(C)]
#[derive(Clone, Copy)]
pub struct Utsname {
    pub sysname: [u8; 256],
    pub nodename: [u8; 256],
    pub release: [u8; 256],
    pub version: [u8; 256],
    pub machine: [u8; 256],
}

impl Default for Utsname {
    fn default() -> Self {
        Utsname {
            sysname: [0; 256],
            nodename: [0; 256],
            release: [0; 256],
            version: [0; 256],
            machine: [0; 256],
        }
    }
}

/// `struct dirent` — 1048 bytes, fixed-size `d_name`.
///
/// Kept under the Linux name because that is what `os::ReadDir` calls
/// it, and the name is a fair warning: this is **not** a header
/// followed by a variable-length name the way `linux_dirent64` is.
/// Darwin's `d_name` is an inline `[c_char; 1024]` and `d_reclen` still
/// varies, so a reader must stride by `d_reclen` while reading exactly
/// `d_namlen` bytes of the name. `d_seekoff` has no Linux counterpart.
#[repr(C)]
#[derive(Clone, Copy, Default)]
#[allow(non_camel_case_types)]
pub struct LinuxDirent64Header {
    pub d_ino: u64,
    pub d_seekoff: u64,
    pub d_reclen: u16,
    pub d_namlen: u16,
    pub d_type: u8,
    // d_name[1024] follows here.
}

/// `struct sigaction` — 16 bytes.
///
/// **`sa_restorer` does not exist.** On amd64 Linux the field is
/// mandatory: the kernel has no sigreturn stub of its own and jumps to
/// whatever userspace supplies. BSD's signal delivery returns through
/// libSystem's own trampoline, so the field is absent from the struct
/// and `SA_RESTORER` is absent from the flags. `sa_mask` is a 32-bit
/// `sigset_t` here (Darwin has 32 signals), not Linux's 64-bit one.
///
/// The field is kept in the goish struct — as a `_sa_restorer_unused`
/// that no wrapper reads — only so the many `Sigaction { .. }`
/// literals across `runtime/` keep compiling. `RtSigaction` on this
/// target translates into the real BSD struct.
#[repr(C)]
#[derive(Clone, Copy, Default)]
pub struct Sigaction {
    pub sa_handler: usize,
    pub sa_flags: u64,
    pub sa_restorer: usize,
    pub sa_mask: u64,
}

/// `stack_t` — 24 bytes. Same three members as Linux's, **in a
/// different order**: `ss_size` precedes `ss_flags` here and follows it
/// there, so this is a genuine re-layout rather than a re-spelling.
#[repr(C)]
#[derive(Clone, Copy, Default)]
#[allow(non_camel_case_types)]
pub struct SigaltstackT {
    pub ss_sp: usize,
    pub ss_size: usize,
    pub ss_flags: i32,
    pub _pad0: i32,
}

/// `struct sockaddr_in` — 16 bytes, same size as Linux's and not the
/// same shape.
///
/// BSD sockaddrs lead with a **length byte**, so `sin_family` is a
/// `u8` at offset 1 rather than a `u16` at offset 0. A `u16` family
/// field holding `AF_INET` would put `2` in `sin_len` and `0` in
/// `sin_family` on this little-endian target — accepted by nothing.
/// Construct through the `SockaddrIn::*` constructors, which set
/// `sin_len` correctly and exist under the same names on both targets.
#[repr(C)]
#[derive(Clone, Copy, Default)]
pub struct SockaddrIn {
    /// Total length of the address, in bytes. BSD-only.
    pub sin_len: u8,
    pub sin_family: u8,
    /// Port number in **network byte order** (big-endian).
    pub sin_port: u16,
    /// IPv4 address in **network byte order** (big-endian).
    pub sin_addr: u32,
    pub _pad: [u8; 8],
}

/// `struct epoll_event` — **Linux-only.** Declared with its Linux shape
/// so `runtime/netpoll` compiles; the Darwin netpoller is kqueue and
/// will bring its own `struct kevent` (M9).
#[repr(C)]
#[derive(Clone, Copy, Default)]
pub struct EpollEvent {
    pub events: u32,
    pub data: u64,
}

/// `struct inotify_event` — **Linux-only**, as above.
#[repr(C)]
#[derive(Clone, Copy, Default)]
#[allow(non_snake_case)]
pub struct InotifyEvent {
    pub Wd: i32,
    pub Mask: u32,
    pub Cookie: u32,
    pub Len: u32,
}

/// `struct fanotify_event_metadata` — **Linux-only**, as above.
#[repr(C)]
#[derive(Clone, Copy, Default)]
#[allow(non_snake_case)]
pub struct FanotifyEventMetadata {
    pub Event_len: u32,
    pub Vers: u8,
    pub Reserved: u8,
    pub Metadata_len: u16,
    pub Mask: u64,
    pub Fd: i32,
    pub Pid: i32,
}

/// `struct fanotify_event_info_header` — **Linux-only**, as above.
#[repr(C)]
#[derive(Clone, Copy, Default)]
#[allow(non_snake_case)]
pub struct FanotifyEventInfoHeader {
    pub Info_type: u8,
    pub Pad: u8,
    pub Len: u16,
}

/// `struct file_handle` — **Linux-only** (`name_to_handle_at(2)`).
#[derive(Clone)]
pub struct FileHandle {
    #[allow(dead_code)]
    pub(crate) handle_type: i32,
    #[allow(dead_code)]
    pub(crate) bytes: crate::slice<u8>,
}

impl core::fmt::Debug for FileHandle {
    fn fmt(&self, f: &mut core::fmt::Formatter<'_>) -> core::fmt::Result {
        write!(f, "FileHandle")
    }
}

/// `struct pollfd` — identical on both targets.
#[repr(C)]
#[derive(Clone, Copy, Default)]
#[allow(non_snake_case)]
pub struct PollFd {
    pub Fd: i32,
    pub Events: i16,
    pub Revents: i16,
}

/// `struct statfs` — 2168 bytes, dominated by two 1024-byte path
/// fields that Linux's 120-byte version does not carry. The goish
/// field names follow Go's `syscall.Statfs_t` for darwin.
///
/// Only `Type` is read outside this package, and it means something
/// different from Linux's: here it is the filesystem type *index*,
/// with the name in `Fstypename`.
#[repr(C)]
#[derive(Clone, Copy)]
#[allow(non_snake_case, non_camel_case_types)]
pub struct Statfs_t {
    pub Bsize: u32,
    pub Iosize: i32,
    pub Blocks: u64,
    pub Bfree: u64,
    pub Bavail: u64,
    pub Files: u64,
    pub Ffree: u64,
    pub Fsid: [i32; 2],
    pub Owner: u32,
    pub Type: u32,
    pub Flags: u32,
    pub Fssubtype: u32,
    pub Fstypename: [u8; 16],
    pub Mntonname: [u8; 1024],
    pub Mntfromname: [u8; 1024],
    pub Flags_ext: u32,
    pub Reserved: [u32; 7],
}

impl Default for Statfs_t {
    fn default() -> Self {
        // `[u8; 1024]` has no `Default`, so this cannot be derived.
        // The struct is plain data with no invalid bit patterns.
        unsafe { core::mem::zeroed() }
    }
}

/// Wrapper handing a raw fd to `net`'s `SyscallConn`. No kernel struct
/// behind it; identical to the Linux definition.
pub struct RawConn {
    pub(super) fd: i32,
}

/// `struct sockaddr_un` — 106 bytes, BSD-shaped: a length byte, a `u8`
/// family, then a **104**-byte path (Linux: `u16` family, 108 bytes).
/// Measured against the SDK. Same constructor surface as the Linux
/// type so `net` builds an AF_UNIX address portably.
#[repr(C)]
#[derive(Clone, Copy)]
pub struct SockaddrUn {
    pub sun_len: u8,
    pub sun_family: u8,
    pub sun_path: [u8; 104],
}

impl SockaddrUn {
    /// An AF_UNIX address for `path`, or None when it does not fit in
    /// `sun_path` with room for the NUL.
    pub fn __for_path(path: &[u8]) -> Option<SockaddrUn> {
        if path.is_empty() || path.len() >= 104 {
            return None;
        }
        let mut sa = SockaddrUn { sun_len: 0, sun_family: super::AF_UNIX as u8, sun_path: [0u8; 104] };
        sa.sun_path[..path.len()].copy_from_slice(path);
        sa.sun_len = sa.__len() as u8;
        Some(sa)
    }

    /// Length to pass to bind/connect: the two header bytes, the path
    /// and its NUL — the same arithmetic as Linux's two-byte family.
    pub fn __len(&self) -> u32 {
        let n = self.sun_path.iter().position(|&b| b == 0).unwrap_or(self.sun_path.len());
        (2 + n + 1) as u32
    }
}

/// `struct itimerval` — 32 bytes, as on Linux. Darwin's `timeval` has a
/// 32-bit `tv_usec` at offset 8 followed by padding; the shared
/// `Timeval` writes it as the low half of an `i64`, which is the same
/// bytes on this little-endian target for any microsecond count.
#[repr(C)]
pub struct Itimerval {
    pub it_interval: crate::os::exec_posix::Timeval,
    pub it_value: crate::os::exec_posix::Timeval,
}
