// go: package reflect
// reflect — Go's `reflect` package, first slice.
//
//   Go                                   goish
//   ──────────────────────────────────   ──────────────────────────────────
//   t := reflect.TypeOf(p)               let t = reflect::TypeOf(&p);
//   t.Name()                             t.Name()
//   t.Kind()                             t.Kind()
//   t.NumField()                         t.NumField()
//   f := t.Field(0)                      let f = t.Field(0);
//   f.Name                               f.Name
//   f.Tag.Get("json")                    f.Tag.Get("json")
//   v, ok := f.Tag.Lookup("xml")         let (v, ok) = f.Tag.Lookup("xml");
//
// Backing: per-struct static `Type` descriptors generated by the
// `#[goish::reflect]` proc-macro. Built-in primitives (bool, int, byte,
// rune, uint, float32, float64, string) get `Reflect` impls in this file.
//
// First slice covers Type/StructField/StructTag and their accessors.
// `Value` (actual data introspection), generic Reflect for slice/map,
// and json integration follow in later iterations.
//
// v1 deviations from Go:
//
//   * `Kind::Int` corresponds to i64 (= goish `int`); there's no separate
//     `Kind::Int64` because `int` IS `i64`. Same for `Kind::Uint` (= u64).
//   * `StructField.Type` is `fn() -> Type` (late binding). Go's
//     `StructField.Type` is a `reflect.Type` interface value, evaluated
//     lazily under the hood. Goish uses the explicit fn-pointer form.
//   * `Reflect` is an opt-in trait. User structs add `#[goish::reflect]`;
//     primitives have impls in this file. Convention: every goish-defined
//     `type X struct` should carry `#[goish::reflect]`.

#![allow(non_snake_case, non_upper_case_globals)]

extern crate alloc;

mod value;
pub use value::New;

use alloc::boxed::Box;
use alloc::vec::Vec;

use crate::goslice::slice;
use crate::gostring::string;
use crate::types::{byte, complex128, float32, float64, int, rune, uint, uintptr};

// ─── Kind ─────────────────────────────────────────────────────────────

/// Mirrors `reflect.Kind`. Numeric ordering matches Go where possible
/// (Invalid = 0; Bool = 1; …) so debug-printing comes out the same.
// Goish v1's `Kind` keeps the original numbering (Invalid=0, Bool=1, …)
// — predates the full Go variant list. Variants added incrementally as
// ports surface them. Where a Go variant has no goish backing type yet
// (Complex64/128, Array stays as a stub), the variant is present so
// match arms compile, but `__reflect_value` never produces it.
#[repr(u8)]
#[derive(Clone, Copy, PartialEq, Eq, Debug, Default)]
pub enum Kind {
    #[default]
    Invalid = 0,
    Bool = 1,
    Int = 2,
    Int8 = 3,
    Int16 = 4,
    Int32 = 5,
    Uint = 6,
    Uint8 = 7,
    Uint16 = 8,
    Uint32 = 9,
    Float32 = 10,
    Float64 = 11,
    String = 12,
    Slice = 13,
    Map = 14,
    Struct = 15,
    Pointer = 16,
    /// Go's `reflect.Interface` (Kind 20). For `any`-typed values whose
    /// dynamic type is opaque from the static descriptor — `__reflect_value`
    /// runtime-downcasts to fill in concrete `Value` variants.
    Interface = 17,
    /// Go: `reflect.Int64`. Goish stores int as i64 so Kind::Int and
    /// Kind::Int64 both apply to int values; ports differentiate via
    /// the explicit type only.
    Int64 = 18,
    /// Go: `reflect.Uint64`. Same convention as Int64.
    Uint64 = 19,
    /// Go: `reflect.Uintptr`. Goish v1 has no `uintptr` distinct from
    /// `uint`; the variant exists so reflect-driven match arms compile.
    Uintptr = 20,
    /// Go: `reflect.Func`. Function-typed values; goish stores as
    /// `Arc<dyn Fn>` and `__reflect_value` returns `Value::Invalid` for
    /// these (we don't introspect callable shapes).
    Func = 21,
    /// Go: `reflect.Chan`. Channels; v1 reflect doesn't introspect.
    Chan = 22,
    /// Go: `reflect.UnsafePointer`. Goish has no `unsafe.Pointer` API;
    /// the variant exists for match-arm parity.
    UnsafePointer = 23,
    /// Go: `reflect.Array`. Fixed-size arrays. Goish slices satisfy
    /// most uses; Kind::Array exists for parity but `__reflect_value`
    /// produces Slice instead.
    Array = 24,
    /// Go: `reflect.Complex64`. Goish has no native complex arithmetic;
    /// `__reflect_value` never produces this variant — it exists so
    /// match arms on Kind compile in ports that mention complex.
    Complex64 = 25,
    /// Go: `reflect.Complex128`. Same caveat as Complex64.
    Complex128 = 26,
}

// Bare `pub const` shortcuts so call sites can write `reflect::Pointer`
// (matching Go's `reflect.Pointer` package-level identifier shape)
// instead of the more verbose `reflect::Kind::Pointer`. Goish ports
// generated by goishc emit the bare form; these consts route to the
// underlying enum variant.
pub const Invalid: Kind = Kind::Invalid;
pub const Bool: Kind = Kind::Bool;
pub const Int: Kind = Kind::Int;
pub const Int8: Kind = Kind::Int8;
pub const Int16: Kind = Kind::Int16;
pub const Int32: Kind = Kind::Int32;
pub const Int64: Kind = Kind::Int64;
pub const Uint: Kind = Kind::Uint;
pub const Uint8: Kind = Kind::Uint8;
pub const Uint16: Kind = Kind::Uint16;
pub const Uint32: Kind = Kind::Uint32;
pub const Uint64: Kind = Kind::Uint64;
pub const Uintptr: Kind = Kind::Uintptr;
pub const Float32: Kind = Kind::Float32;
pub const Float64: Kind = Kind::Float64;
pub const String: Kind = Kind::String;
pub const Slice: Kind = Kind::Slice;
pub const Map: Kind = Kind::Map;
pub const Struct: Kind = Kind::Struct;
pub const Pointer: Kind = Kind::Pointer;
pub const Interface: Kind = Kind::Interface;
pub const Func: Kind = Kind::Func;
pub const Chan: Kind = Kind::Chan;
pub const UnsafePointer: Kind = Kind::UnsafePointer;
pub const Array: Kind = Kind::Array;
pub const Complex64: Kind = Kind::Complex64;
pub const Complex128: Kind = Kind::Complex128;
/// `reflect.Ptr` — older Go name for `reflect.Pointer`. Some ports still
/// use the legacy spelling (Go 1.18 renamed it). Same value as `Pointer`.
pub const Ptr: Kind = Kind::Pointer;

// go: none — goish idiom: Go's `fmt` finds `Kind.String` by structural
// assertion, so `%v` on a Kind prints "struct". goish's printer
// dispatches on `Format`, reached through `Stringer`, and nothing
// implemented it — a Kind could not be printed at all, which is the
// same gap io/fs's FileMode had.
impl crate::fmt::Stringer for Kind {
    // go: none — goish idiom: see the note above this impl.
    fn String(&self) -> string {
        // Method-call form, not `Kind::String(self)`: the enum has a
        // `String` VARIANT, which shadows the method in path position.
        let k: &Kind = self;
        return k.String();
    }
}

// go: none — goish idiom: as for Kind. Go's `%v` on a reflect.Type
// prints the type's name through its String method.
impl crate::fmt::Stringer for Type {
    // go: none — goish idiom: see the note above this impl.
    fn String(&self) -> string {
        let ty: &Type = self;
        return ty.String();
    }
}

impl Kind {
    /// Mirrors Go's `Kind.String()` — lowercase Go type name.
    pub fn String(&self) -> string {
        let s = match self {
            Kind::Invalid => "invalid",
            Kind::Bool => "bool",
            Kind::Int => "int",
            Kind::Int8 => "int8",
            Kind::Int16 => "int16",
            Kind::Int32 => "int32",
            Kind::Uint => "uint",
            Kind::Uint8 => "uint8",
            Kind::Uint16 => "uint16",
            Kind::Uint32 => "uint32",
            Kind::Float32 => "float32",
            Kind::Float64 => "float64",
            Kind::String => "string",
            Kind::Slice => "slice",
            Kind::Map => "map",
            Kind::Struct => "struct",
            Kind::Interface => "interface",
            Kind::Int64 => "int64",
            Kind::Uint64 => "uint64",
            Kind::Uintptr => "uintptr",
            Kind::Func => "func",
            Kind::Chan => "chan",
            Kind::UnsafePointer => "unsafe.Pointer",
            Kind::Array => "array",
            Kind::Pointer => "ptr",
            Kind::Complex64 => "complex64",
            Kind::Complex128 => "complex128",
        };
        string::from_static(s)
    }
}

// ─── StructTag ────────────────────────────────────────────────────────

/// Mirrors `reflect.StructTag`. Holds the raw tag string verbatim
/// (e.g. `r#"json:"name" xml:"name,attr""#`) and parses on demand.
///
/// Constructors are `__new` (private path) so `#[goish::reflect]` can
/// embed it in static descriptors.
#[derive(Clone, Copy)]
pub struct StructTag {
    raw: &'static str,
}

impl StructTag {
    /// Internal constructor used by the `#[goish::reflect]` macro and
    /// by built-in Reflect impls. Empty string means "no tag".
    #[doc(hidden)]
    pub const fn __new(raw: &'static str) -> Self {
        Self { raw }
    }

    // go: none — goish idiom: Go's `StructTag` IS a string
    // (`type StructTag string`), so a caller writes `string(f.Tag)` to
    // read the raw text back — for a log line, or to re-derive
    // something the accessors do not expose. goish's is a struct with
    // a private field and offered no way at all, which made the raw
    // tag unreachable from outside this file.
    pub fn String(&self) -> string {
        return string::from_bytes(self.raw.as_bytes());
    }

    /// `Get(key)` — value for `key`, empty string if missing.
    /// Mirrors Go's `StructTag.Get`.
    ///
    /// Takes `impl AsRef<str>` so call sites can pass either a string
    /// literal (`"json"`) or a Goish `string` value — both deref to
    /// `&str` for the lookup. Goish ports often call `Tag.Get(string("json"))`
    /// because Go's source side has no `&str` distinction; widening
    /// the param is the priority #2 "Go idioms first" pattern from
    /// CLAUDE.md.
    pub fn Get<S: AsRef<[byte]>>(&self, key: S) -> string {
        let (v, _) = self.Lookup(key);
        v
    }

    /// `Lookup(key)` — `(value, ok)`. `ok` distinguishes "absent" from
    /// "present with empty value". Verbatim port of Go 1.25
    /// `reflect.StructTag.Lookup` (reflect/type.go:1056). Same widened
    /// param as `Get`.
    pub fn Lookup<S: AsRef<[byte]>>(&self, key: S) -> (string, bool) {
        let key_bytes = key.as_ref();
        let mut tag = self.raw.as_bytes();

        while !tag.is_empty() {
            // Skip leading space.
            let mut i = 0;
            while i < tag.len() && tag[i] == b' ' {
                i += 1;
            }
            tag = &tag[i..];
            if tag.is_empty() {
                break;
            }

            // Scan to colon. A space, quote, or control char is a syntax error.
            i = 0;
            while i < tag.len()
                && tag[i] > b' '
                && tag[i] != b':'
                && tag[i] != b'"'
                && tag[i] != 0x7f
            {
                i += 1;
            }
            if i == 0 || i + 1 >= tag.len() || tag[i] != b':' || tag[i + 1] != b'"' {
                break;
            }
            let name = &tag[..i];
            tag = &tag[i + 1..];

            // Scan quoted string.
            i = 1;
            while i < tag.len() && tag[i] != b'"' {
                if tag[i] == b'\\' {
                    i += 1;
                }
                i += 1;
            }
            if i >= tag.len() {
                break;
            }
            let qvalue = &tag[..i + 1];
            tag = &tag[i + 1..];

            if key_bytes == name {
                if let Some(v) = unquote_tag_value(qvalue) {
                    return (v, true);
                }
                break;
            }
        }
        (string::new(), false)
    }
}

/// Strip surrounding `"` and apply Go string-literal escape rules to the
/// inside. Returns `None` on malformed input (mirrors strconv.Unquote err).
fn unquote_tag_value(q: &[u8]) -> Option<string> {
    if q.len() < 2 || q[0] != b'"' || q[q.len() - 1] != b'"' {
        return None;
    }
    let inner = &q[1..q.len() - 1];
    let mut out: alloc::vec::Vec<u8> = alloc::vec::Vec::with_capacity(inner.len());
    let mut i = 0;
    while i < inner.len() {
        let c = inner[i];
        if c != b'\\' {
            out.push(c);
            i += 1;
            continue;
        }
        // escape sequence
        i += 1;
        if i >= inner.len() {
            return None;
        }
        match inner[i] {
            b'"' => out.push(b'"'),
            b'\\' => out.push(b'\\'),
            b'/' => out.push(b'/'),
            b'n' => out.push(b'\n'),
            b'r' => out.push(b'\r'),
            b't' => out.push(b'\t'),
            b'a' => out.push(0x07),
            b'b' => out.push(0x08),
            b'f' => out.push(0x0C),
            b'v' => out.push(0x0B),
            b'0' => out.push(0),
            b'\'' => out.push(b'\''),
            // \xNN / \uNNNN are not parsed in v1 — tag values almost
            // never use them in practice. Add when needed.
            _ => return None,
        }
        i += 1;
    }
    Some(string::__from_vec(out))
}

// ─── StructField ──────────────────────────────────────────────────────

/// Mirrors `reflect.StructField`. Held by value inside a `Type`'s field
/// table. `Type` is a fn pointer for late binding (breaks recursion when
/// a struct field type is itself a Reflect type that hasn't been defined
/// when the descriptor is built).
#[derive(Clone, Copy)]
pub struct StructField {
    pub Name: &'static str,
    pub Tag: StructTag,
    pub Type: fn() -> Type,
    /// Mirrors `reflect.StructField.PkgPath` — non-empty marks the
    /// field unexported. Goish currently exposes only exported fields
    /// via `#[goish::reflect]`, so this is always `""`. Present so
    /// ports that test `f.PkgPath != ""` skip-unexported branches
    /// compile and behave as no-ops.
    pub PkgPath: &'static str,
    /// Mirrors `reflect.StructField.Anonymous` — true for embedded
    /// (no-name) fields. Goish's reflect descriptor doesn't yet model
    /// embedding, so this is always `false`. Present so ports that
    /// branch on `f.Anonymous` for embedded-walk compile.
    pub Anonymous: bool,
}

// ─── Type ─────────────────────────────────────────────────────────────

/// Mirrors `reflect.Type`. The struct is value-typed; `TypeOf` returns
/// it by value (cheap — a few words). `elem` and `key` carry late-bound
/// element/key descriptors for Slice / Map / Pointer kinds.
///
/// Eq/Ord/Hash compare by `(kind, name)` — same identity Go uses for
/// `reflect.Type` (each named type is unique, and Type is comparable).
/// This lets `map<reflect::Type, V>` and `map[reflect::Type] = ...` work
/// in Go ports that key caches on type.
#[derive(Clone, Copy)]
pub struct Type {
    kind: Kind,
    name: &'static str,
    fields: &'static [StructField],
    elem: Option<fn() -> Type>,
    key: Option<fn() -> Type>,
}

impl PartialEq for Type {
    fn eq(&self, other: &Self) -> bool {
        self.kind == other.kind && self.name == other.name
    }
}
impl Eq for Type {}
impl PartialOrd for Type {
    fn partial_cmp(&self, other: &Self) -> Option<core::cmp::Ordering> {
        Some(self.cmp(other))
    }
}
impl Ord for Type {
    fn cmp(&self, other: &Self) -> core::cmp::Ordering {
        (self.kind as u8, self.name).cmp(&(other.kind as u8, other.name))
    }
}
impl core::hash::Hash for Type {
    fn hash<H: core::hash::Hasher>(&self, state: &mut H) {
        (self.kind as u8).hash(state);
        self.name.hash(state);
    }
}

impl crate::gomap::GoHash for Type {
    fn go_hash(&self, seed: u64) -> u64 {
        crate::gomap::hash_bytes(self.name.as_bytes(), seed)
    }
}

impl Type {
    /// Internal constructor for `#[goish::reflect]` and built-in impls.
    #[doc(hidden)]
    pub const fn __new(kind: Kind, name: &'static str, fields: &'static [StructField]) -> Self {
        Self {
            kind,
            name,
            fields,
            elem: None,
            key: None,
        }
    }

    /// Builder hook for slice/pointer/map element types.
    #[doc(hidden)]
    pub const fn __with_elem(self, e: fn() -> Type) -> Self {
        Self {
            elem: Some(e),
            ..self
        }
    }

    /// Builder hook for map key types.
    #[doc(hidden)]
    pub const fn __with_key(self, k: fn() -> Type) -> Self {
        Self {
            key: Some(k),
            ..self
        }
    }

    // go: none — goish-only: the read side of [`Type::__with_elem`].
    //
    // `Elem()` hands back the element *descriptor*; constructing a
    // `Value::Slice` needs the late-bound `fn() -> Type` itself, because
    // that is what the variant stores and what `Value::Type()` calls to
    // rebuild the slice type. Go has no analogue — `reflect.MakeSlice`
    // takes the slice `Type` and the runtime already knows its element —
    // so this is the goish shape of that step, used by
    // `encoding/asn1`'s `parseSequenceOf`.
    #[doc(hidden)]
    pub fn __elem_fn(&self) -> Option<fn() -> Type> {
        return self.elem;
    }

    // go: none — goish idiom: the `key` mirror of `__elem_fn`, for
    // `Zero(Kind::Map)`, which needs a non-optional `fn() -> Type` for
    // both halves of `Value::Map`.
    #[doc(hidden)]
    pub fn __key_fn(&self) -> Option<fn() -> Type> {
        return self.key;
    }

    /// `Name()` — declared type name as goish `string`, or empty
    /// string for unnamed types. (Internal: the underlying field is
    /// `&'static str` since the name comes from the
    /// `#[goish::reflect]` proc-macro at compile time; we wrap it
    /// in a `string` at the API boundary.)
    pub fn Name(&self) -> crate::gostring::string {
        crate::gostring::string::from_static(self.name)
    }

    /// `Kind()` — kind tag.
    pub fn Kind(&self) -> Kind {
        self.kind
    }

    /// `NumField()` — number of struct fields. Panics in Go for non-struct
    /// kinds; here we return 0 (less surprising for boilerplate code).
    pub fn NumField(&self) -> int {
        self.fields.len() as int
    }

    /// `Field(i)` — i-th struct field. Panics if out of range.
    pub fn Field(&self, i: int) -> StructField {
        if i < 0 || (i as usize) >= self.fields.len() {
            panic!("reflect: Field index out of bounds");
        }
        self.fields[i as usize]
    }

    /// `FieldByName(name)` — `(field, ok)`. Linear scan.
    ///
    /// Takes `name: &str` for the same literal-friendliness reason as
    /// `StructTag::Get`.
    pub fn FieldByName(&self, name: &str) -> (StructField, bool) {
        for f in self.fields {
            if f.Name.as_bytes() == name.as_bytes() {
                return (*f, true);
            }
        }
        (
            StructField {
                Name: "",
                Tag: StructTag::__new(""),
                Type: || Type::__new(Kind::Invalid, "", &[]),
                PkgPath: "",
                Anonymous: false,
            },
            false,
        )
    }

    /// `Elem()` — element type for Slice / Map / Pointer. Panics for
    /// other kinds, mirroring Go.
    pub fn Elem(&self) -> Type {
        match self.elem {
            Some(f) => f(),
            None => panic!("reflect: Elem of type that has no element"),
        }
    }

    /// `Key()` — key type for Map. Panics for other kinds.
    pub fn Key(&self) -> Type {
        match self.key {
            Some(f) => f(),
            None => panic!("reflect: Key of non-map type"),
        }
    }

    /// `Comparable()` — Go semantics. Primitives + Pointer + (Struct of
    /// comparables) are comparable; Slice and Map are not.
    pub fn Comparable(&self) -> bool {
        match self.kind {
            Kind::Bool
            | Kind::Int
            | Kind::Int8
            | Kind::Int16
            | Kind::Int32
            | Kind::Uint
            | Kind::Uint8
            | Kind::Uint16
            | Kind::Uint32
            | Kind::Float32
            | Kind::Float64
            | Kind::String
            | Kind::Pointer => true,
            Kind::Slice | Kind::Map => false,
            Kind::Struct => self.fields.iter().all(|f| (f.Type)().Comparable()),
            // Interface comparability depends on the dynamic type — Go
            // returns true (the comparison may panic at runtime if the
            // dynamic type is non-comparable). v1 follows Go.
            Kind::Interface => true,
            Kind::Int64 | Kind::Uint64 | Kind::Uintptr => true,
            Kind::Func | Kind::Chan | Kind::UnsafePointer => false,
            Kind::Array => self.fields.iter().all(|f| (f.Type)().Comparable()),
            // Complex types are comparable in Go (==/!= use IEEE-754 rules).
            // Goish v1 has no native complex arithmetic; this arm exists for
            // parity so reflect-driven match-on-Kind compiles.
            Kind::Complex64 | Kind::Complex128 => true,
            Kind::Invalid => false,
        }
    }

    /// `AssignableTo(u)` — v1 simplification: Kind must match; for named
    /// types Name must match; for slice/map element & key types must be
    /// recursively assignable. (Go's full interface-satisfaction logic
    /// is out of scope until goish gains an interface type.)
    pub fn AssignableTo(&self, u: &Type) -> bool {
        if self.kind != u.kind {
            return false;
        }
        if !self.name.is_empty() || !u.name.is_empty() {
            return self.name == u.name;
        }
        match self.kind {
            Kind::Slice => {
                if self.elem.is_none() || u.elem.is_none() {
                    return false;
                }
                self.Elem().AssignableTo(&u.Elem())
            }
            Kind::Map => {
                if self.elem.is_none() || u.elem.is_none() || self.key.is_none() || u.key.is_none()
                {
                    return false;
                }
                self.Key().AssignableTo(&u.Key()) && self.Elem().AssignableTo(&u.Elem())
            }
            _ => true,
        }
    }

    /// `FieldByIndex(index)` — nested field by index path. Mirrors
    /// Go's `Type.FieldByIndex`. Panics on out-of-range.
    pub fn FieldByIndex(&self, index: &[int]) -> StructField {
        let mut t = *self;
        let mut f: Option<StructField> = None;
        for (i, &x) in index.iter().enumerate() {
            if i > 0 {
                t = match f {
                    Some(ff) => (ff.Type)(),
                    None => t,
                };
            }
            f = Some(t.Field(x));
        }
        f.expect("reflect: FieldByIndex with empty index")
    }

    /// `FieldByIndexErr(index)` — `(field, error)` form. In goish this
    /// is equivalent to `FieldByIndex` (we don't traverse pointers, so
    /// the "indirection through nil" error case Go raises doesn't
    /// arise). Provided for API parity.
    pub fn FieldByIndexErr(&self, index: &[int]) -> (StructField, crate::error) {
        (self.FieldByIndex(index), crate::errors::nil)
    }

    /// `FieldByNameFunc(match)` — find first field whose name satisfies
    /// `match`. Returns `(field, ok)`.
    pub fn FieldByNameFunc<F: Fn(&str) -> bool>(&self, m: F) -> (StructField, bool) {
        for f in self.fields {
            if m(f.Name) {
                return (*f, true);
            }
        }
        (
            StructField {
                Name: "",
                Tag: StructTag::__new(""),
                Type: || Type::__new(Kind::Invalid, "", &[]),
                PkgPath: "",
                Anonymous: false,
            },
            false,
        )
    }

    /// `OverflowInt(x)` — true if `x` is out of range for this signed-int
    /// type. Panics for non-int kinds.
    pub fn OverflowInt(&self, x: int) -> bool {
        let bit_size = match self.kind {
            Kind::Int => 64,
            Kind::Int8 => 8,
            Kind::Int16 => 16,
            Kind::Int32 => 32,
            _ => panic!("reflect.Type.OverflowInt of non-int"),
        };
        if bit_size == 64 {
            return false;
        }
        let shift = 64 - bit_size;
        let trunc = (x << shift) >> shift;
        x != trunc
    }

    /// `OverflowUint(x)` — true if `x` is out of range for this
    /// unsigned-int type.
    pub fn OverflowUint(&self, x: uint) -> bool {
        let bit_size = match self.kind {
            Kind::Uint => 64,
            Kind::Uint8 => 8,
            Kind::Uint16 => 16,
            Kind::Uint32 => 32,
            _ => panic!("reflect.Type.OverflowUint of non-uint"),
        };
        if bit_size == 64 {
            return false;
        }
        let shift = 64 - bit_size;
        let trunc = (x << shift) >> shift;
        x != trunc
    }

    /// `OverflowFloat(x)` — true if `x` cannot be represented in this
    /// float type without losing magnitude.
    pub fn OverflowFloat(&self, x: float64) -> bool {
        match self.kind {
            Kind::Float64 => false,
            Kind::Float32 => {
                let ax = if x < 0.0 { -x } else { x };
                ax > float32::MAX as float64
            }
            _ => panic!("reflect.Type.OverflowFloat of non-float"),
        }
    }

    // go: sdk 1.25.5 reflect/type.go:588-597 rtype.Bits
    /// `Bits()` — the size of the type in bits. Panics if the kind is not
    /// one of the sized or unsized Int, Uint, Float, or Complex kinds.
    ///
    /// Go reads the runtime's `Size_`; goish's descriptor has no layout,
    /// so the width comes from the kind. `int`/`uint`/`uintptr` are 64
    /// bits, which is what they are on every target goish builds for.
    pub fn Bits(&self) -> int {
        return match self.kind {
            Kind::Int8 | Kind::Uint8 => 8,
            Kind::Int16 | Kind::Uint16 => 16,
            Kind::Int32 | Kind::Uint32 | Kind::Float32 => 32,
            Kind::Int | Kind::Int64 | Kind::Uint | Kind::Uint64 | Kind::Uintptr | Kind::Float64
            | Kind::Complex64 => 64,
            Kind::Complex128 => 128,
            _ => panic!("reflect: Bits of non-arithmetic Type {}", self.String()),
        };
    }

    /// `String()` — readable type name. `[]int`, `map[string]int`,
    /// `*Person`, `Person`, `int`, etc. Mirrors Go's `Type.String()`.
    pub fn String(&self) -> string {
        match self.kind {
            Kind::Slice => {
                let mut out: alloc::vec::Vec<u8> = b"[]".to_vec();
                if let Some(e) = self.elem {
                    out.extend_from_slice(e().String().as_bytes());
                }
                string::__from_vec(out)
            }
            Kind::Map => {
                let mut out: alloc::vec::Vec<u8> = b"map[".to_vec();
                if let Some(k) = self.key {
                    out.extend_from_slice(k().String().as_bytes());
                }
                out.push(b']');
                if let Some(e) = self.elem {
                    out.extend_from_slice(e().String().as_bytes());
                }
                string::__from_vec(out)
            }
            Kind::Pointer => {
                let mut out: alloc::vec::Vec<u8> = b"*".to_vec();
                if let Some(e) = self.elem {
                    out.extend_from_slice(e().String().as_bytes());
                }
                string::__from_vec(out)
            }
            _ => {
                if self.name.is_empty() {
                    self.kind.String()
                } else {
                    string::from_static(self.name)
                }
            }
        }
    }
}

// ─── Value ────────────────────────────────────────────────────────────
//
// Read-only value introspection. Unlike Go's `reflect.Value` (fat
// pointer over the original storage), goish's `Value` is a deep-cloned
// enum — every `ValueOf(&x)` walks `x` once and copies its data into
// the variant. Trade: copies on construction; gain: no unsafe pointer
// arithmetic, no offset_of needed, lifetime-free at the user surface.
//
// Mutation (`SetBool`, `SetString`, etc.) requires the pointer-form and
// is deferred to a later iteration.

/// Mirrors `reflect.Value` (read-only).
///
/// `Default` returns `Value::Invalid` — matches Go's zero-`reflect.Value`,
/// where `IsValid()` is false. Ports that hold a `reflect::Value` field
/// (e.g. kylelemons' `formatter.cur`) rely on this to derive `Default`.
#[derive(Clone, Default)]
pub enum Value {
    #[default]
    Invalid,
    Bool(bool),
    Int(int),
    Int8(i8),
    Int16(i16),
    Int32(i32), // covers rune
    Uint(uint),
    Uint8(u8), // covers byte
    Uint16(u16),
    Uint32(u32),
    Float32(float32),
    Float64(float64),
    String(string),
    Slice {
        elem_type: fn() -> Type,
        items: Vec<Value>,
    },
    Map {
        key_type: fn() -> Type,
        value_type: fn() -> Type,
        /// (key, value) pairs in stable order. Goish's `map<K,V>` is
        /// BTreeMap-backed, so this list is key-sorted; that's also the
        /// order we use for json.Marshal output.
        entries: Vec<(Value, Value)>,
    },
    Struct {
        ty: Type,
        fields: Vec<Value>,
    },
    Pointer(Box<Value>),
    /// A *named* type whose underlying kind is not a struct — Go's
    /// `type ObjectIdentifier []int`, `type Enumerated int`.
    ///
    /// Every other variant reconstructs its `Type` from the variant tag
    /// alone, which is right for `int` and `[]int` and wrong the moment a
    /// port declares a name over one: the name is what distinguishes
    /// `asn1.ObjectIdentifier` from any other `[]int`, and losing it made
    /// `encoding/asn1`'s makeBody encode an OID as a SEQUENCE OF INTEGER.
    /// Struct-shaped named types were already fine — `Struct` carries its
    /// `ty` — so this covers the rest.
    ///
    /// Everything but `Type()` delegates to `inner`, so a `Named` behaves
    /// exactly like the value it wraps.
    Named {
        ty: Type,
        inner: Box<Value>,
    },
}

// `PartialEq` is hand-written rather than derived: `Slice` and `Map`
// carry their element/key/value types as `fn() -> Type` constructors, and
// deriving would compare those *pointers*. Function-pointer addresses are
// not guaranteed unique — the linker may merge identical functions, and
// the same function can land at different addresses across codegen units
// — so a derived `==` could call two identically-typed slices unequal, or
// two differently-typed ones equal. Resolve the constructor and compare
// the `Type`, which has the identity semantics Go's `reflect.Type` uses
// (kind + name). Every other variant compares exactly as the derive did.
impl PartialEq for Value {
    // go: none — goish-only: Go's reflect.Value comparison has no direct
    // analogue (Go compares the underlying values via Interface()); this
    // is the structural equality goish ports rely on.
    fn eq(&self, other: &Self) -> bool {
        return match (self, other) {
            (Value::Invalid, Value::Invalid) => true,
            (Value::Bool(a), Value::Bool(b)) => a == b,
            (Value::Int(a), Value::Int(b)) => a == b,
            (Value::Int8(a), Value::Int8(b)) => a == b,
            (Value::Int16(a), Value::Int16(b)) => a == b,
            (Value::Int32(a), Value::Int32(b)) => a == b,
            (Value::Uint(a), Value::Uint(b)) => a == b,
            (Value::Uint8(a), Value::Uint8(b)) => a == b,
            (Value::Uint16(a), Value::Uint16(b)) => a == b,
            (Value::Uint32(a), Value::Uint32(b)) => a == b,
            (Value::Float32(a), Value::Float32(b)) => a == b,
            (Value::Float64(a), Value::Float64(b)) => a == b,
            (Value::String(a), Value::String(b)) => a == b,
            (
                Value::Slice {
                    elem_type: ea,
                    items: ia,
                },
                Value::Slice {
                    elem_type: eb,
                    items: ib,
                },
            ) => ea() == eb() && ia == ib,
            (
                Value::Map {
                    key_type: ka,
                    value_type: va,
                    entries: ea,
                },
                Value::Map {
                    key_type: kb,
                    value_type: vb,
                    entries: eb,
                },
            ) => ka() == kb() && va() == vb() && ea == eb,
            (Value::Struct { ty: ta, fields: fa }, Value::Struct { ty: tb, fields: fb }) => {
                ta == tb && fa == fb
            }
            (Value::Pointer(a), Value::Pointer(b)) => a == b,
            (Value::Named { ty: ta, inner: ia }, Value::Named { ty: tb, inner: ib }) => {
                ta == tb && ia == ib
            }
            _ => false,
        };
    }
}

impl Value {
    /// `Kind()` — runtime tag.
    pub fn Kind(&self) -> Kind {
        match self {
            Value::Named { inner, .. } => inner.Kind(),
            Value::Invalid => Kind::Invalid,
            Value::Bool(_) => Kind::Bool,
            Value::Int(_) => Kind::Int,
            Value::Int8(_) => Kind::Int8,
            Value::Int16(_) => Kind::Int16,
            Value::Int32(_) => Kind::Int32,
            Value::Uint(_) => Kind::Uint,
            Value::Uint8(_) => Kind::Uint8,
            Value::Uint16(_) => Kind::Uint16,
            Value::Uint32(_) => Kind::Uint32,
            Value::Float32(_) => Kind::Float32,
            Value::Float64(_) => Kind::Float64,
            Value::String(_) => Kind::String,
            Value::Slice { .. } => Kind::Slice,
            Value::Map { .. } => Kind::Map,
            Value::Struct { .. } => Kind::Struct,
            Value::Pointer(_) => Kind::Pointer,
        }
    }

    /// `Type()` — descriptor of this value's type.
    pub fn Type(&self) -> Type {
        match self {
            // The whole point of the variant: a named type keeps its name.
            Value::Named { ty, .. } => *ty,
            Value::Struct { ty, .. } => *ty,
            Value::Slice { elem_type, .. } => {
                Type::__new(Kind::Slice, "", &[]).__with_elem(*elem_type)
            }
            Value::Map {
                key_type,
                value_type,
                ..
            } => Type::__new(Kind::Map, "", &[])
                .__with_key(*key_type)
                .__with_elem(*value_type),
            _ => Type::__new(self.Kind(), self.Kind().__static_name(), &[]),
        }
    }

    /// `IsValid()` — false for the zero-Value (`Value::Invalid`).
    pub fn IsValid(&self) -> bool {
        if let Value::Named { inner, .. } = self {
            return inner.IsValid();
        }
        !matches!(self, Value::Invalid)
    }

    /// `IsZero()` — true if the value is its type's zero value. Mirrors
    /// Go's `reflect.Value.IsZero`.
    pub fn IsZero(&self) -> bool {
        match self {
            Value::Named { inner, .. } => inner.IsZero(),
            Value::Invalid => true,
            Value::Bool(b) => !*b,
            Value::Int(n) => *n == 0,
            Value::Int8(n) => *n == 0,
            Value::Int16(n) => *n == 0,
            Value::Int32(n) => *n == 0,
            Value::Uint(n) => *n == 0,
            Value::Uint8(n) => *n == 0,
            Value::Uint16(n) => *n == 0,
            Value::Uint32(n) => *n == 0,
            Value::Float32(f) => *f == 0.0,
            Value::Float64(f) => *f == 0.0,
            Value::String(s) => s.as_bytes().is_empty(),
            Value::Slice { items, .. } => items.is_empty(),
            Value::Map { entries, .. } => entries.is_empty(),
            Value::Struct { fields, .. } => fields.iter().all(Value::IsZero),
            Value::Pointer(_) => false,
        }
    }

    /// `Bool()` — panics if Kind != Bool.
    pub fn Bool(&self) -> bool {
        if let Value::Named { inner, .. } = self {
            return inner.Bool();
        }
        match self {
            Value::Bool(b) => *b,
            _ => panic!("reflect.Value.Bool of non-bool"),
        }
    }

    /// `Int()` — typed accessor for any signed-int kind. Panics otherwise.
    pub fn Int(&self) -> int {
        if let Value::Named { inner, .. } = self {
            return inner.Int();
        }
        match self {
            Value::Int(n) => *n,
            Value::Int8(n) => *n as int,
            Value::Int16(n) => *n as int,
            Value::Int32(n) => *n as int,
            _ => panic!("reflect.Value.Int of non-int"),
        }
    }

    /// `Uint()` — any unsigned-int kind. Panics otherwise.
    pub fn Uint(&self) -> uint {
        if let Value::Named { inner, .. } = self {
            return inner.Uint();
        }
        match self {
            Value::Uint(n) => *n,
            Value::Uint8(n) => *n as uint,
            Value::Uint16(n) => *n as uint,
            Value::Uint32(n) => *n as uint,
            _ => panic!("reflect.Value.Uint of non-uint"),
        }
    }

    /// `Float()` — float32 or float64. Panics otherwise.
    pub fn Float(&self) -> float64 {
        if let Value::Named { inner, .. } = self {
            return inner.Float();
        }
        match self {
            Value::Float32(f) => *f as float64,
            Value::Float64(f) => *f,
            _ => panic!("reflect.Value.Float of non-float"),
        }
    }

    /// `String()` — string value, or kind label for non-strings (matches
    /// Go: `reflect.Value.String` returns `"<int Value>"` for non-string).
    pub fn String(&self) -> string {
        match self {
            Value::String(s) => s.clone(),
            _ => self.Kind().String(),
        }
    }

    /// `Len()` — element count for slice/string/map. Panics otherwise.
    pub fn Len(&self) -> int {
        if let Value::Named { inner, .. } = self {
            return inner.Len();
        }
        match self {
            Value::Slice { items, .. } => items.len() as int,
            Value::String(s) => s.as_bytes().len() as int,
            Value::Map { entries, .. } => entries.len() as int,
            _ => panic!("reflect.Value.Len of non-slice/string/map"),
        }
    }

    /// `Cap()` — capacity for slice. Goish slices are deep-cloned and
    /// don't track capacity separately from length, so `Cap == Len`.
    /// Panics for non-slice (matches Go for non-Array/Chan/Slice).
    pub fn Cap(&self) -> int {
        if let Value::Named { inner, .. } = self {
            return inner.Cap();
        }
        match self {
            Value::Slice { items, .. } => items.len() as int,
            _ => panic!("reflect.Value.Cap of non-slice"),
        }
    }

    /// `IsNil()` — Go semantics for nil-able kinds:
    ///   * Pointer: inner is `Value::Invalid`
    ///   * Slice / Map: always `false` in goish v1 (we don't track nil
    ///     vs empty distinctly; an empty slice is non-nil-empty)
    ///   * Other kinds: panic
    pub fn IsNil(&self) -> bool {
        if let Value::Named { inner, .. } = self {
            return inner.IsNil();
        }
        match self {
            Value::Slice { .. } => false,
            Value::Map { .. } => false,
            Value::Pointer(inner) => matches!(**inner, Value::Invalid),
            // Func / Chan / Interface / UnsafePointer don't have a
            // primitive variant in goish v1; reflect-driven IsNil
            // checks (e.g. typeutils.IsNil) just return false here.
            // Real callers wanting nil-detection on these should use
            // the typed `== nil` comparison instead.
            Value::Invalid => true,
            _ => false,
        }
    }

    /// `reflect.Value.Interface()` (Go 1.25 `src/reflect/value.go`) —
    /// extracts the underlying value as `interface{}`. Goish models
    /// `interface{}` as `Arc<dyn Any + Send + Sync>`. Round-trips
    /// through known Value variants; `Invalid` and unsupported variants
    /// box `()` as a placeholder so call sites still get something.
    pub fn Interface(&self) -> alloc::sync::Arc<dyn core::any::Any + Send + Sync> {
        if let Value::Named { inner, .. } = self {
            return inner.Interface();
        }
        match self {
            Value::Bool(b) => alloc::sync::Arc::new(*b),
            Value::Int(n) => alloc::sync::Arc::new(*n),
            Value::Int8(n) => alloc::sync::Arc::new(*n),
            Value::Int16(n) => alloc::sync::Arc::new(*n),
            Value::Int32(n) => alloc::sync::Arc::new(*n),
            Value::Uint(n) => alloc::sync::Arc::new(*n),
            Value::Uint8(n) => alloc::sync::Arc::new(*n),
            Value::Uint16(n) => alloc::sync::Arc::new(*n),
            Value::Uint32(n) => alloc::sync::Arc::new(*n),
            Value::Float32(f) => alloc::sync::Arc::new(*f),
            Value::Float64(f) => alloc::sync::Arc::new(*f),
            Value::String(s) => alloc::sync::Arc::new(s.clone()),
            // Slice/Map/Struct/Pointer/Invalid: box `()` as placeholder.
            // A future port that needs typed re-extraction can extend
            // each variant with the original payload via `Arc<dyn Any>`
            // stored alongside.
            _ => alloc::sync::Arc::new(()),
        }
    }

    /// `Bytes()` — convert a `Value::Slice` whose element kind is
    /// `Uint8` into a `slice<byte>`. Panics otherwise.
    pub fn Bytes(&self) -> slice<byte> {
        if let Value::Named { inner, .. } = self {
            return inner.Bytes();
        }
        match self {
            Value::Slice { items, elem_type } if elem_type().Kind() == Kind::Uint8 => {
                let mut out: Vec<byte> = Vec::with_capacity(items.len());
                for item in items {
                    out.push(match item {
                        Value::Uint8(b) => *b,
                        _ => 0,
                    });
                }
                slice::__from_vec(out)
            }
            _ => panic!("reflect.Value.Bytes of non-byte slice"),
        }
    }

    /// `Slice(low, high)` — sub-slice via reflect. Mirrors Go's
    /// `Value.Slice` for slice/string. Panics for other kinds.
    pub fn Slice(&self, low: int, high: int) -> Value {
        match self {
            Value::Slice { elem_type, items } => {
                let lo = low as usize;
                let hi = high as usize;
                let sub = items[lo..hi].to_vec();
                Value::Slice {
                    elem_type: *elem_type,
                    items: sub,
                }
            }
            Value::String(s) => {
                let bytes = s.as_bytes();
                let lo = low as usize;
                let hi = high as usize;
                Value::String(string::from_bytes(&bytes[lo..hi]))
            }
            _ => panic!("reflect.Value.Slice of non-slice/string"),
        }
    }

    /// `Slice3(low, high, max)` — explicit-cap variant. Goish slices are
    /// deep-cloned, so the cap argument is ignored; semantically
    /// identical to `Slice(low, high)`.
    pub fn Slice3(&self, low: int, high: int, _max: int) -> Value {
        self.Slice(low, high)
    }

    /// `Elem()` — for Pointer: the inner Value. For other kinds, panics
    /// (matches Go's reflect.Value.Elem semantics for the cases goish
    /// supports — Interface kind is out-of-scope).
    pub fn Elem(&self) -> Value {
        match self {
            Value::Pointer(inner) => (**inner).clone(),
            _ => panic!("reflect.Value.Elem: not a pointer"),
        }
    }

    /// `FieldByIndex(index)` — nested field access by index path.
    /// Mirrors Go's `Value.FieldByIndex`. Walks struct → struct → ...
    pub fn FieldByIndex(&self, index: &[int]) -> Value {
        let mut v = self.clone();
        for (i, &x) in index.iter().enumerate() {
            if i > 0 {
                if let Value::Pointer(_) = v {
                    v = v.Elem();
                }
            }
            v = v.Field(x);
        }
        v
    }

    /// `OverflowInt(x)` — true if `x` cannot be represented in this
    /// signed-int Value's type. Mirrors Go's bit-shift truncation test.
    pub fn OverflowInt(&self, x: int) -> bool {
        let bit_size = match self.Kind() {
            Kind::Int => 64,
            Kind::Int8 => 8,
            Kind::Int16 => 16,
            Kind::Int32 => 32,
            _ => panic!("reflect.Value.OverflowInt of non-int"),
        };
        if bit_size == 64 {
            return false;
        }
        let shift = 64 - bit_size;
        let trunc = (x << shift) >> shift;
        x != trunc
    }

    /// `OverflowUint(x)` — counterpart of `OverflowInt` for unsigned.
    pub fn OverflowUint(&self, x: uint) -> bool {
        let bit_size = match self.Kind() {
            Kind::Uint => 64,
            Kind::Uint8 => 8,
            Kind::Uint16 => 16,
            Kind::Uint32 => 32,
            _ => panic!("reflect.Value.OverflowUint of non-uint"),
        };
        if bit_size == 64 {
            return false;
        }
        let shift = 64 - bit_size;
        let trunc = (x << shift) >> shift;
        x != trunc
    }

    /// `OverflowFloat(x)` — true if `x` cannot be represented in this
    /// float Value's type without loss of magnitude.
    pub fn OverflowFloat(&self, x: float64) -> bool {
        match self.Kind() {
            Kind::Float64 => false,
            Kind::Float32 => {
                let ax = if x < 0.0 { -x } else { x };
                ax > float32::MAX as float64
            }
            _ => panic!("reflect.Value.OverflowFloat of non-float"),
        }
    }

    /// `MapKeys()` — keys in stable (sorted) order, as `slice<Value>`
    /// (Go's `[]Value`). Panics if not Map.
    pub fn MapKeys(&self) -> crate::goslice::slice<Value> {
        if let Value::Named { inner, .. } = self {
            return inner.MapKeys();
        }
        match self {
            Value::Map { entries, .. } => {
                let v: Vec<Value> = entries.iter().map(|(k, _)| k.clone()).collect();
                crate::goslice::slice::__from_vec(v)
            }
            _ => panic!("reflect.Value.MapKeys of non-map"),
        }
    }

    /// `MapIndex(key)` — value for key, or `Value::Invalid` if absent.
    /// Linear scan for v1 (entries are sorted; we could binary-search
    /// over comparable keys, but v1 keeps it straightforward).
    pub fn MapIndex(&self, key: &Value) -> Value {
        if let Value::Named { inner, .. } = self {
            return inner.MapIndex(key);
        }
        match self {
            Value::Map { entries, .. } => {
                for (k, v) in entries {
                    if value_eq(k, key) {
                        return v.clone();
                    }
                }
                Value::Invalid
            }
            _ => panic!("reflect.Value.MapIndex of non-map"),
        }
    }

    /// `Index(i)` — i-th element of a slice. Panics if not Slice.
    pub fn Index(&self, i: int) -> Value {
        if let Value::Named { inner, .. } = self {
            return inner.Index(i);
        }
        match self {
            Value::Slice { items, .. } => items[i as usize].clone(),
            _ => panic!("reflect.Value.Index of non-slice"),
        }
    }

    /// `NumField()` — struct field count. Panics if not Struct.
    pub fn NumField(&self) -> int {
        match self {
            Value::Struct { ty, .. } => ty.NumField(),
            _ => panic!("reflect.Value.NumField of non-struct"),
        }
    }

    /// `Field(i)` — i-th field of a struct. Panics if not Struct.
    pub fn Field(&self, i: int) -> Value {
        match self {
            Value::Struct { fields, .. } => fields[i as usize].clone(),
            _ => panic!("reflect.Value.Field of non-struct"),
        }
    }

    /// `FieldByName(name)` — looks up by name. Returns `Value::Invalid`
    /// if not found.
    pub fn FieldByName(&self, name: &str) -> Value {
        match self {
            Value::Struct { ty, fields } => {
                for i in 0..ty.fields.len() {
                    if ty.fields[i].Name.as_bytes() == name.as_bytes() {
                        return fields[i].clone();
                    }
                }
                Value::Invalid
            }
            _ => panic!("reflect.Value.FieldByName of non-struct"),
        }
    }

    /// `CanInterface()` — whether `Interface()` is callable without panic.
    ///
    /// Go's semantics also returns false for unexported struct fields
    /// accessed via reflection; goish v1 does not track export status
    /// per Value, so we conservatively return true for every valid
    /// Value. Ports using this as a `Interface()` precondition (e.g.
    /// kylelemons pretty-printer) get the same outcome as Go.
    pub fn CanInterface(&self) -> bool {
        self.IsValid()
    }

    /// `Pointer()` — address as uintptr.
    ///
    /// Goish v1's `Value` is owned-tree-shaped, not pointer-shaped, so
    /// no real machine address exists for primitive variants. For
    /// `Value::Pointer(b)` we return the stable address of the boxed
    /// inner (valid for `self`'s lifetime). For other kinds we return
    /// 0. Sufficient for cycle-detection patterns (kylelemons walks
    /// pointer values to detect cycles); semantically degraded vs. Go
    /// for callers that round-trip through pointer arithmetic.
    pub fn Pointer(&self) -> uintptr {
        match self {
            Value::Pointer(b) => (&**b as *const Value) as uintptr,
            _ => 0,
        }
    }

    /// `Complex()` — `complex128` accessor.
    ///
    /// Goish v1 has no complex variant on `Value` (Kind::Complex64/128
    /// exist only for match-arm parity). Returns `(0.0, 0.0)` so
    /// format-only call sites compile. Real complex arithmetic is not
    /// supported in v1 — a port that does math on the result must be
    /// hand-tuned.
    pub fn Complex(&self) -> complex128 {
        (0.0, 0.0)
    }

    /// `Call(args)` — invoke a `Kind::Func` value with the given args.
    ///
    /// Goish v1's `Value` does not model `Kind::Func` (functions
    /// aren't introspectable via reflection in v1). Always returns an
    /// empty result slice. Ports that rely on dynamic reflective
    /// dispatch (e.g. kylelemons calling a user-supplied `Formatter`)
    /// fall through to the non-reflect path — visible behaviour is a
    /// no-op, not a panic.
    pub fn Call(&self, _args: crate::goslice::slice<Value>) -> crate::goslice::slice<Value> {
        crate::goslice::slice::default()
    }
}

/// Structural equality for use by `MapIndex`. Compares by Kind and
/// payload. Sufficient for json-shaped lookups (string keys); for
/// general use the `reflect.DeepEqual` port (later iteration) will be
/// the public API.
fn value_eq(a: &Value, b: &Value) -> bool {
    match (a, b) {
        (Value::Invalid, Value::Invalid) => true,
        (Value::Bool(x), Value::Bool(y)) => x == y,
        (Value::Int(x), Value::Int(y)) => x == y,
        (Value::Int8(x), Value::Int8(y)) => x == y,
        (Value::Int16(x), Value::Int16(y)) => x == y,
        (Value::Int32(x), Value::Int32(y)) => x == y,
        (Value::Uint(x), Value::Uint(y)) => x == y,
        (Value::Uint8(x), Value::Uint8(y)) => x == y,
        (Value::Uint16(x), Value::Uint16(y)) => x == y,
        (Value::Uint32(x), Value::Uint32(y)) => x == y,
        (Value::Float32(x), Value::Float32(y)) => x == y,
        (Value::Float64(x), Value::Float64(y)) => x == y,
        (Value::String(x), Value::String(y)) => x == y,
        _ => false,
    }
}

impl Kind {
    fn __static_name(&self) -> &'static str {
        match self {
            Kind::Invalid => "",
            Kind::Bool => "bool",
            Kind::Int => "int",
            Kind::Int8 => "int8",
            Kind::Int16 => "int16",
            Kind::Int32 => "int32",
            Kind::Uint => "uint",
            Kind::Uint8 => "uint8",
            Kind::Uint16 => "uint16",
            Kind::Uint32 => "uint32",
            Kind::Float32 => "float32",
            Kind::Float64 => "float64",
            Kind::String => "string",
            Kind::Slice => "",
            Kind::Map => "",
            Kind::Struct => "",
            Kind::Pointer => "",
            Kind::Interface => "interface{}",
            Kind::Int64 => "int64",
            Kind::Uint64 => "uint64",
            Kind::Uintptr => "uintptr",
            Kind::Func => "",
            Kind::Chan => "",
            Kind::UnsafePointer => "",
            Kind::Array => "",
            Kind::Complex64 => "complex64",
            Kind::Complex128 => "complex128",
        }
    }
}

// ─── Reflect trait ────────────────────────────────────────────────────

/// Trait implemented by every type whose `reflect.TypeOf` is supported.
/// Built-in primitives have impls in this file; user structs get them
/// from `#[goish::reflect]`.
pub trait Reflect {
    /// Returns the descriptor by value. Cheap — just a few words.
    fn __reflect_type() -> Type;

    /// Returns a deep-cloned `Value` mirror of `self`. Used by
    /// `reflect::ValueOf` and tag-driven `json.Marshal`.
    fn __reflect_value(&self) -> Value;
}

// Blanket impl: `&T: Reflect` when `T: Reflect`. Goish ports often
// pass `&val` to `reflect::ValueOf` (mirroring Go's value-style
// `reflect.ValueOf(val)` — except Go's interface{} arg auto-borrows
// where Rust's `&T` does not). The transpiler emits `ValueOf(&val)`
// uniformly; this blanket keeps the call valid whether `val` is a
// concrete `T` or already a borrow.
impl<T: Reflect + ?Sized> Reflect for &T {
    #[inline]
    fn __reflect_type() -> Type {
        T::__reflect_type()
    }
    #[inline]
    fn __reflect_value(&self) -> Value {
        (**self).__reflect_value()
    }
}

/// `reflect.TypeOf(v)` — descriptor for `v`'s static type.
pub fn TypeOf<T: Reflect + ?Sized>(_: &T) -> Type {
    T::__reflect_type()
}

/// Type-only entry point: returns the reflect descriptor for `T` without
/// requiring a value of T. Mirrors Go's `reflect.TypeOf((*T)(nil)).Elem()`
/// idiom — used to fetch the descriptor of an interface (where a real
/// value would need a concrete carrier).
pub fn TypeOfDyn<T: Reflect + ?Sized>() -> Type {
    T::__reflect_type()
}

/// `reflect.ValueOf(v)` — read-only `Value` mirror of `v`.
pub fn ValueOf<T: Reflect + ?Sized>(v: &T) -> Value {
    v.__reflect_value()
}

// ─── ValueOfAny / TypeOfAny — reflection out of `goish::Any` ─────────
//
// Go needs no such pair: `reflect.ValueOf` takes `any`, and an
// interface header always carries its dynamic type descriptor, so
// reflecting an erased value is the *only* thing reflect does.
//
// Goish has two type-erasure mechanisms with different jobs.
// `goany::Any` erases into `Arc<dyn AnyVal>` and gives downcast;
// `Reflect` gives `Value`/`Type` but is not object safe
// (`__reflect_type()` has no `self`), so a `dyn` cannot carry it.
// Until now the two did not meet, and `crypto/x509/pkix` sat at 5/6
// because `asn1.Marshal(tv.Value)` needs exactly this crossing.
//
// The crossing is made at the *wrap* site, not the read site:
// `Any::new` requires `T: Reflect` and stores both answers in the
// `AnyVal` vtable (see goany.rs). These two functions read them.
//
// The comma-ok return is the load-bearing part. `ok == false` means
// "this carrier has no reflection" — a closure, or a value wrapped
// with `Any::new_opaque`. It is NOT the same as
// `(Value::Invalid, true)`, which is the honest reflection of `nil`
// (Go's `reflect.ValueOf(nil)` is likewise the zero Value). A caller
// that will go on to marshal must be able to tell those apart: one is
// Go's "cannot marshal nil value", the other has no Go analogue at all
// and has to name the offending type. Returning `Value::Invalid` for
// both would make `asn1.Marshal` quietly emit the wrong diagnosis, and
// - through pkix's `typeName = oidString` fallback - the wrong string.

// go: none — goish idiom: Go's `reflect.ValueOf` already takes `any`.
// This is that function for goish's `Any` carrier, with the extra `ok`
// Go does not need. See the note above for why `ok` is not optional.
/// `reflect.ValueOf(x)` where `x` is a type-erased `goish::Any`.
///
/// Returns `(value, true)` when the wrapped payload was stored through
/// [`goany::Any::new`](crate::goany::Any::new) (which requires
/// `Reflect`), and `(Value::Invalid, false)` when it was stored through
/// `new_fn` / `new_opaque` and genuinely has no reflection.
pub fn ValueOfAny(v: &crate::goany::Any) -> (Value, bool) {
    return match v.0.__goish_reflect_value() {
        Some(val) => (val, true),
        None => (Value::Invalid, false),
    };
}

// go: none — goish idiom: the `Type` half of `ValueOfAny`. Go spells
// this `reflect.TypeOf(x)`; goish's `TypeOf` needs a static `T`, which
// an erased value does not have.
/// `reflect.TypeOf(x)` where `x` is a type-erased `goish::Any` — the
/// *dynamic* type descriptor, not `interface{}`.
///
/// Same `ok` contract as [`ValueOfAny`]. Note that
/// `<Any as Reflect>::__reflect_type()` cannot answer this: it has no
/// `self`, so all it can say is `interface{}`.
pub fn TypeOfAny(v: &crate::goany::Any) -> (Type, bool) {
    return match v.0.__goish_reflect_type() {
        Some(t) => (t, true),
        None => (Type::__new(Kind::Invalid, "", &[]), false),
    };
}

// ─── AnyReflect — type-erased reflection ─────────────────────────────
//
// Ports that accept arbitrary user values (logr's structured logging
// slots, json.Marshal's `any`, query.Values's interface{}, …) used to
// take `Arc<dyn core::any::Any>`. That handles concrete-type downcast
// but loses access to reflection — funcr renders unknown types as
// `"<unhandled>"`.
//
// `AnyReflect` is the supertrait that bundles both: implementers are
// `Any` (downcast-capable) AND `Reflect` (walkable via Value). The
// blanket impl below makes every `Reflect + Any + Send + Sync` type
// pick this up for free, including all `#[goish::reflect]`-tagged
// user structs and the built-in primitives.
//
// Migration path for ports: change `Arc<dyn Any + Send + Sync>` to
// `Arc<dyn AnyReflect + Send + Sync>`. Existing `downcast_ref::<T>()`
// call sites work unchanged through the `as_any()` upcast helper;
// new sites can call `.__reflect_value()` directly to get a Value.

/// Type-erased reflection handle. Combines `core::any::Any` (typeid-
/// based downcast) with goish's `Reflect` (Value walking). Use
/// `Arc<dyn AnyReflect + Send + Sync>` in port APIs that accept Go's
/// `interface{}` / `any` values.
pub trait AnyReflect: core::any::Any + Send + Sync {
    /// Upcast to `&dyn Any` so existing `Any::downcast_ref::<T>()`
    /// call sites keep working without restructuring.
    fn as_any(&self) -> &dyn core::any::Any;
    /// Walk the value into a `reflect::Value`. Same semantics as
    /// `Reflect::__reflect_value` — provided here so callers with
    /// only an `&dyn AnyReflect` reference can introspect without a
    /// concrete type.
    fn reflect_value(&self) -> Value;
    /// Return the `reflect::Type` descriptor for this value's
    /// static (concrete) type. Mirrors `Reflect::__reflect_type`.
    fn reflect_type(&self) -> Type;
}

impl<T> AnyReflect for T
where
    T: core::any::Any + Reflect + Send + Sync,
{
    fn as_any(&self) -> &dyn core::any::Any {
        self
    }
    fn reflect_value(&self) -> Value {
        <T as Reflect>::__reflect_value(self)
    }
    fn reflect_type(&self) -> Type {
        <T as Reflect>::__reflect_type()
    }
}

/// `reflect.Zero(t)` (Go 1.25 `src/reflect/value.go`) — the zero
/// `Value` for type `t`. The returned value is neither addressable nor
/// settable.
///
/// Struct and Slice used to fall into an `Invalid` bucket, "until ports
/// surface a need". Three surfaced it, and two of them are bugs the
/// first hid:
///
///   * `encoding/asn1`'s `parseSequenceOf` must hand `parseField` an
///     element of the right type before there is any data in it —
///     literally Go's `reflect.Append(ret, reflect.Zero(elemType))`.
///
///   * `encoding/asn1`'s `makeField` omits an `asn1:"optional"` field by
///     testing `v == Zero(v.Type())` (marshal.rs:1134). With `Invalid` on
///     the right-hand side that test never fired for a struct- or
///     slice-shaped field, so an empty `asn1.RawValue` or a nil
///     `asn1.ObjectIdentifier` was *encoded* where Go omits it — visible
///     as `MarshalPKCS8PrivateKey` emitting a curve OID Go leaves out,
///     and as an empty parameters element inside every
///     `AlgorithmIdentifier` Go writes bare, which is every Ed25519 and
///     ECDSA one. That last put `MarshalPKIXPublicKey` and every
///     certificate built on it two bytes off Go.
///
/// A named non-struct type is re-wrapped in `Value::Named` so its zero
/// keeps the name — the same reason the variant exists at all, and what
/// `getUniversalType` matches an `ObjectIdentifier` (and a
/// `RelativeDistinguishedNameSET`) on. `Struct` already carries its
/// `ty`, so its arm returns early and skips the wrapper; wrapping it
/// would make a reflected struct unequal to its own zero and re-open
/// the OPTIONAL bug above.
///
/// `time::Time` and `big::Int` remain unmatchable, unavoidably: both
/// report *no* fields (Go's are unexported) while their
/// `__reflect_value` carries two synthetic ones, so a descriptor-driven
/// zero cannot equal their real zero. The error is in the safe
/// direction — an optional `time::Time` is emitted where Go would omit
/// it, never omitted where Go emits it.
pub fn Zero(t: Type) -> Value {
    let inner = match t.Kind() {
        Kind::Bool => Value::Bool(false),
        Kind::Int => Value::Int(0),
        Kind::Int8 => Value::Int8(0),
        Kind::Int16 => Value::Int16(0),
        Kind::Int32 => Value::Int32(0),
        Kind::Int64 => Value::Int(0),
        Kind::Uint => Value::Uint(0),
        Kind::Uint8 => Value::Uint8(0),
        Kind::Uint16 => Value::Uint16(0),
        Kind::Uint32 => Value::Uint32(0),
        Kind::Uint64 => Value::Uint(0),
        Kind::Uintptr => Value::Uint(0),
        Kind::Float32 => Value::Float32(0.0),
        Kind::Float64 => Value::Float64(0.0),
        Kind::String => Value::String(string::from_static("")),
        Kind::Struct => {
            // Early `return`, deliberately: `Value::Struct` already
            // carries its `ty`, and falling through to the `Named`
            // wrapper below would make a reflected struct unequal to
            // its own zero.
            let mut fields: Vec<Value> = Vec::new();
            let nf = t.NumField();
            let mut i: int = 0;
            while i < nf {
                fields.push(Zero((t.Field(i).Type)()));
                i += 1;
            }
            return Value::Struct { ty: t, fields };
        }
        // A nil slice and an empty one are the same value in goish
        // (goslice.rs:167), so the zero slice is the empty one — with
        // the element type preserved so `Type()` still answers.
        Kind::Slice => match t.__elem_fn() {
            Some(elem_type) => Value::Slice {
                elem_type,
                items: Vec::new(),
            },
            None => Value::Invalid,
        },
        Kind::Map => match (t.__key_fn(), t.__elem_fn()) {
            (Some(key_type), Some(value_type)) => Value::Map {
                key_type,
                value_type,
                entries: Vec::new(),
            },
            _ => Value::Invalid,
        },
        // Go's zero pointer is nil; `Value::Pointer(Invalid)` is the
        // encoding `IsNil` already recognises.
        Kind::Pointer => Value::Pointer(alloc::boxed::Box::new(Value::Invalid)),
        // The zero interface is nil *with a type*. Early `return`, like
        // Struct: the value must carry `t` itself, and the `Named`
        // wrapper below would re-wrap it.
        //
        // Go's `reflect.Zero(interfaceType)` yields a Value whose
        // `Type()` is that interface, which is what `encoding/asn1`'s
        // `parseField` dispatches an ASN.1 ANY on. Falling through to
        // `Invalid` here lost the type, so `parseSequenceOf` handed
        // `parseField` a typeless destination and every `asn1.Unmarshal`
        // into a SEQUENCE OF reaching a `pkix.AttributeTypeAndValue`
        // — every X.509 Name, so every CRL — died with "unknown Go
        // type: invalid".
        Kind::Interface => {
            return Value::Named {
                ty: t,
                inner: alloc::boxed::Box::new(Value::Invalid),
            }
        }
        // Array/Interface/Func/Chan still fall back.
        _ => Value::Invalid,
    };
    // "Named" here means *declared* — `asn1.Enumerated`, not `int`. Every
    // primitive `Type` carries its kind's static name ("int", "bool"),
    // and the matching `Value` variants carry no name at all, so wrapping
    // those would make `Zero(int)` unequal to a reflected `int` and break
    // exactly the OPTIONAL-omission test this function feeds.
    if inner.IsValid() && t.Name().Len() > 0 && t.Name() != t.Kind().__static_name() {
        return Value::Named {
            ty: t,
            inner: Box::new(inner),
        };
    }
    return inner;
}

// ─── FromReflectValue — typed setter dispatch ─────────────────────────
//
// Mirrors `json::FromValue` but over `reflect::Value`. Used by macro-
// emitted `Settable::__reflect_set_field` implementations to safely
// extract the typed payload from a Value at runtime.

pub trait FromReflectValue: Sized {
    fn from_reflect_value(v: Value) -> (Self, crate::error);
}

macro_rules! impl_from_reflect {
    ($t:ty, $variant:ident, $name:expr) => {
        impl FromReflectValue for $t {
            fn from_reflect_value(v: Value) -> (Self, crate::error) {
                match v {
                    Value::$variant(x) => (x, crate::errors::nil),
                    _ => (
                        <$t as Default>::default(),
                        crate::errors::New(concat!("reflect: expected ", $name)),
                    ),
                }
            }
        }
    };
}

impl_from_reflect!(bool, Bool, "bool");
impl_from_reflect!(int, Int, "int");
impl_from_reflect!(i8, Int8, "int8");
impl_from_reflect!(i16, Int16, "int16");
impl_from_reflect!(rune, Int32, "int32");
impl_from_reflect!(uint, Uint, "uint");
impl_from_reflect!(byte, Uint8, "uint8");
impl_from_reflect!(u16, Uint16, "uint16");
impl_from_reflect!(u32, Uint32, "uint32");
impl_from_reflect!(float32, Float32, "float32");
impl_from_reflect!(float64, Float64, "float64");
impl_from_reflect!(string, String, "string");

impl<T: FromReflectValue + Clone + Default> FromReflectValue for slice<T> {
    fn from_reflect_value(v: Value) -> (Self, crate::error) {
        match v {
            Value::Slice { items, .. } => {
                let mut out: Vec<T> = Vec::with_capacity(items.len());
                for item in items {
                    let (elem, err) = T::from_reflect_value(item);
                    if err != crate::errors::nil {
                        return (slice::__from_vec(Vec::new()), err);
                    }
                    out.push(elem);
                }
                (slice::__from_vec(out), crate::errors::nil)
            }
            _ => (
                slice::__from_vec(Vec::new()),
                crate::errors::New("reflect: expected slice"),
            ),
        }
    }
}

impl<K, V> FromReflectValue for crate::gomap::map<K, V>
where
    K: FromReflectValue + crate::gomap::GoHash + PartialEq + Default + Clone,
    V: FromReflectValue + Default + Clone,
{
    fn from_reflect_value(v: Value) -> (Self, crate::error) {
        match v {
            Value::Map { entries, .. } => {
                let mut out = crate::gomap::map::<K, V>::new();
                for (kv, vv) in entries {
                    let (k, err) = K::from_reflect_value(kv);
                    if err != crate::errors::nil {
                        return (crate::gomap::map::<K, V>::new(), err);
                    }
                    let (v, err) = V::from_reflect_value(vv);
                    if err != crate::errors::nil {
                        return (crate::gomap::map::<K, V>::new(), err);
                    }
                    out.Set(k, v);
                }
                (out, crate::errors::nil)
            }
            _ => (
                crate::gomap::map::<K, V>::new(),
                crate::errors::New("reflect: expected map"),
            ),
        }
    }
}

// ─── Mutation: SetField / SetFieldByName ──────────────────────────────
//
// Goish doesn't expose Go's `Value.Field(i).SetInt(99)` chain directly
// (that requires per-field offsets + bounded unsafe). Instead, the
// `#[goish::reflect]` macro emits a `Settable` impl per struct that
// dispatches a typed setter per field index. The free functions below
// route through that protocol — type-checked, no unsafe.
//
//   reflect::SetField(&mut p, 1, Value::Int(99))
//   reflect::SetFieldByName(&mut p, "Name", Value::String(string("a")))

/// Trait emitted by `#[goish::reflect]` for user structs. Allows
/// runtime "write field i with this Value" without unsafe.
pub trait Settable {
    /// Assigns `v` into the i-th field. Returns `nil` on success or a
    /// type-mismatch / out-of-range error.
    fn __reflect_set_field(&mut self, idx: int, v: Value) -> crate::error;
}

/// `reflect.SetField(&mut t, idx, v)` — write `v` into the i-th field.
pub fn SetField<T: Settable>(target: &mut T, idx: int, v: Value) -> crate::error {
    target.__reflect_set_field(idx, v)
}

/// `reflect.SetFieldByName(&mut t, name, v)` — look up the field by
/// declared name and write `v` into it. Returns an error if the field
/// is not found.
pub fn SetFieldByName<T: Settable + Reflect>(target: &mut T, name: &str, v: Value) -> crate::error {
    let ty = T::__reflect_type();
    for i in 0..ty.NumField() {
        if ty.Field(i).Name.as_bytes() == name.as_bytes() {
            return target.__reflect_set_field(i, v);
        }
    }
    crate::errors::New("reflect.SetFieldByName: field not found")
}

/// `reflect.Indirect(v)` — if `v` is a `Pointer`, returns the inner
/// value; otherwise returns `v` unchanged. Mirrors Go's `Indirect`.
pub fn Indirect(v: Value) -> Value {
    match v {
        Value::Pointer(_) => v.Elem(),
        _ => v,
    }
}

/// `reflect.Append(s, x...)` — append values to a `Value::Slice`.
/// Returns a new Value (goish slices are deep-cloned, so the caller
/// receives an independent copy).
pub fn Append(s: Value, items: &[Value]) -> Value {
    match s {
        Value::Slice {
            elem_type,
            items: mut existing,
        } => {
            existing.reserve(items.len());
            for x in items {
                existing.push(x.clone());
            }
            Value::Slice {
                elem_type,
                items: existing,
            }
        }
        _ => panic!("reflect.Append: not a slice"),
    }
}

/// `reflect.AppendSlice(s, t)` — append all of `t`'s items to `s`.
/// `t` must also be a `Value::Slice`.
pub fn AppendSlice(s: Value, t: Value) -> Value {
    let extra = match t {
        Value::Slice { items, .. } => items,
        _ => panic!("reflect.AppendSlice: src is not a slice"),
    };
    Append(s, &extra)
}

/// `reflect.VisibleFields(t)` — flat field list as `slice<StructField>`
/// (Go's `[]StructField`). In Go this walks embedded fields BFS;
/// goish v1 has no embedded fields, so this is the same as iterating
/// `Field(0..NumField())`.
pub fn VisibleFields(t: Type) -> crate::goslice::slice<StructField> {
    let n = t.NumField();
    let mut out: alloc::vec::Vec<StructField> = alloc::vec::Vec::with_capacity(n as usize);
    for i in 0..n {
        out.push(t.Field(i));
    }
    crate::goslice::slice::__from_vec(out)
}

/// `reflect.DeepEqual(x, y)` — structural equality between any two
/// reflectable values. Mirrors Go 1.25 `reflect.DeepEqual`:
///
///   * primitives compare with `==` (NaN != NaN, matching Go)
///   * slices: same length + element-wise DeepEqual
///   * maps: same length + every key has a deeply-equal value
///   * structs: same struct name + element-wise DeepEqual
///   * Invalid == Invalid
///   * different Kinds → unequal
///
/// Goish's `Value` is an acyclic deep-clone, so the visited-set
/// short-circuit Go's implementation needs (for cyclic pointer/map
/// graphs) is unnecessary here.
pub fn DeepEqual<T, U>(x: &T, y: &U) -> bool
where
    T: Reflect + ?Sized,
    U: Reflect + ?Sized,
{
    deep_value_equal(&ValueOf(x), &ValueOf(y))
}

fn deep_value_equal(a: &Value, b: &Value) -> bool {
    if a.Kind() != b.Kind() {
        return false;
    }
    match (a, b) {
        (Value::Invalid, Value::Invalid) => true,
        (Value::Bool(x), Value::Bool(y)) => x == y,
        (Value::Int(x), Value::Int(y)) => x == y,
        (Value::Int8(x), Value::Int8(y)) => x == y,
        (Value::Int16(x), Value::Int16(y)) => x == y,
        (Value::Int32(x), Value::Int32(y)) => x == y,
        (Value::Uint(x), Value::Uint(y)) => x == y,
        (Value::Uint8(x), Value::Uint8(y)) => x == y,
        (Value::Uint16(x), Value::Uint16(y)) => x == y,
        (Value::Uint32(x), Value::Uint32(y)) => x == y,
        // NaN != NaN, matching Go.
        (Value::Float32(x), Value::Float32(y)) => x == y,
        (Value::Float64(x), Value::Float64(y)) => x == y,
        (Value::String(x), Value::String(y)) => x == y,
        (Value::Slice { items: ai, .. }, Value::Slice { items: bi, .. }) => {
            if ai.len() != bi.len() {
                return false;
            }
            ai.iter()
                .zip(bi.iter())
                .all(|(x, y)| deep_value_equal(x, y))
        }
        (Value::Map { entries: ae, .. }, Value::Map { entries: be, .. }) => {
            if ae.len() != be.len() {
                return false;
            }
            // Go semantics: each key in a must map to a deeply-equal value
            // in b. Keys are sorted in our representation, but matching
            // by lookup keeps us correct even if invariants drift.
            for (ka, va) in ae {
                let mut matched = false;
                for (kb, vb) in be {
                    if deep_value_equal(ka, kb) {
                        if !deep_value_equal(va, vb) {
                            return false;
                        }
                        matched = true;
                        break;
                    }
                }
                if !matched {
                    return false;
                }
            }
            true
        }
        (Value::Struct { fields: af, ty: ta }, Value::Struct { fields: bf, ty: tb }) => {
            // Distinct named struct types are never deeply equal — even
            // if their field shapes coincide.
            if ta.Name() != tb.Name() {
                return false;
            }
            if af.len() != bf.len() {
                return false;
            }
            af.iter()
                .zip(bf.iter())
                .all(|(x, y)| deep_value_equal(x, y))
        }
        (Value::Pointer(pa), Value::Pointer(pb)) => deep_value_equal(pa, pb),
        _ => false,
    }
}

// ─── Built-in Reflect impls ───────────────────────────────────────────

macro_rules! impl_primitive_reflect {
    ($t:ty, $kind:expr, $name:literal, $variant:ident, $($conv:tt)*) => {
        impl Reflect for $t {
            #[inline]
            fn __reflect_type() -> Type {
                Type::__new($kind, $name, &[])
            }
            #[inline]
            fn __reflect_value(&self) -> Value {
                Value::$variant($($conv)*(*self))
            }
        }
    };
}

// Identity conversion (no-op).
fn id<T>(x: T) -> T {
    x
}

impl_primitive_reflect!(bool, Kind::Bool, "bool", Bool, id);
impl_primitive_reflect!(int, Kind::Int, "int", Int, id);
impl_primitive_reflect!(i8, Kind::Int8, "int8", Int8, id);
impl_primitive_reflect!(i16, Kind::Int16, "int16", Int16, id);
// rune = i32, so the i32 impl covers both the explicit-int32 and the
// rune use — same as Go where `type rune = int32` shares Kind::Int32.
impl_primitive_reflect!(rune, Kind::Int32, "int32", Int32, id);
impl_primitive_reflect!(uint, Kind::Uint, "uint", Uint, id);
// byte = u8, mirrors Go (`type byte = uint8`).
impl_primitive_reflect!(byte, Kind::Uint8, "uint8", Uint8, id);
impl_primitive_reflect!(u16, Kind::Uint16, "uint16", Uint16, id);
impl_primitive_reflect!(u32, Kind::Uint32, "uint32", Uint32, id);
impl_primitive_reflect!(float32, Kind::Float32, "float32", Float32, id);
impl_primitive_reflect!(float64, Kind::Float64, "float64", Float64, id);

// `string` doesn't fit the macro (Clone, not Copy); spell it out.
impl Reflect for string {
    #[inline]
    fn __reflect_type() -> Type {
        Type::__new(Kind::String, "string", &[])
    }
    #[inline]
    fn __reflect_value(&self) -> Value {
        Value::String(self.clone())
    }
}

// `error` lowers as an interface type for reflection purposes — its
// dynamic shape is whatever concrete error implementer holds the Arc.
// Mirrors Go's `reflect.TypeOf(err)` returning the interface descriptor
// (or the dynamic type if non-nil).
impl Reflect for crate::errors::error {
    #[inline]
    fn __reflect_type() -> Type {
        Type::__new(Kind::Interface, "error", &[])
    }
    #[inline]
    fn __reflect_value(&self) -> Value {
        Value::String(crate::gostring::string::from_static("error"))
    }
}

// `interface{}` reflection — Go's `var x any = …` carries the dynamic
// type that reflect.ValueOf reads at runtime. Goish models `any` as
// `Arc<dyn core::any::Any + Send + Sync>`. `__reflect_type()` is
// static so it returns Kind::Interface; `__reflect_value()` runtime-
// downcasts to a known set of primitive types and falls back to
// Value::Invalid for unrecognised payloads. Equivalent to fmt::Sprintv's
// downcast table — extend the type list there and here together when
// new ports surface needs.
impl Reflect for alloc::sync::Arc<dyn core::any::Any + Send + Sync> {
    #[inline]
    fn __reflect_type() -> Type {
        Type::__new(Kind::Interface, "interface{}", &[])
    }
    fn __reflect_value(&self) -> Value {
        let any: &(dyn core::any::Any + Send + Sync) = self.as_ref();
        if let Some(v) = any.downcast_ref::<string>() {
            return Value::String(v.clone());
        }
        if let Some(v) = any.downcast_ref::<i64>() {
            return Value::Int(*v);
        }
        if let Some(v) = any.downcast_ref::<i32>() {
            return Value::Int32(*v);
        }
        if let Some(v) = any.downcast_ref::<u64>() {
            return Value::Uint(*v);
        }
        if let Some(v) = any.downcast_ref::<u32>() {
            return Value::Uint32(*v);
        }
        if let Some(v) = any.downcast_ref::<u8>() {
            return Value::Uint8(*v);
        }
        if let Some(v) = any.downcast_ref::<f64>() {
            return Value::Float64(*v);
        }
        if let Some(v) = any.downcast_ref::<f32>() {
            return Value::Float32(*v);
        }
        if let Some(v) = any.downcast_ref::<bool>() {
            return Value::Bool(*v);
        }
        // Unrecognised concrete type — fall back to Invalid (DeepEqual
        // treats Invalid==Invalid as true). Future ports needing
        // recursive struct-of-Any comparison should extend the table
        // alongside fmt::Sprintv's downcast list.
        Value::Invalid
    }
}

// `goish::Any` (interface{} newtype). This used to be a nine-entry
// `downcast_ref` probe table over the primitives, with `Value::Invalid`
// for everything else — a `pkix.Name` inside an `Any` reflected as
// "nil". It now reads the reflection the wrap site recorded, so every
// `Any::new`-constructed value reflects, not just the nine.
//
// The `Value::Invalid` fallback that remains is for the two payloads
// that really have none (`new_fn`, `new_opaque`). `Reflect` has no
// failure channel — `__reflect_value` must return *some* Value — which
// is exactly why [`ValueOfAny`] exists and why every consumer that will
// act on the result (marshal it, walk it, encode it) must go through
// that comma-ok form instead of `ValueOf`. Landing on Invalid here is
// still safe rather than silent: `asn1::makeField` rejects an invalid
// Value. It is merely less precise about *why*.
impl Reflect for crate::goany::Any {
    #[inline]
    fn __reflect_type() -> Type {
        // Static type only — `Reflect::__reflect_type` has no `self`,
        // so the dynamic answer is unreachable from here. Callers that
        // want it use `TypeOfAny`.
        Type::__new(Kind::Interface, "interface{}", &[])
    }
    fn __reflect_value(&self) -> Value {
        let (v, ok) = ValueOfAny(self);
        if ok {
            return v;
        }
        // A nil (or non-reflectable) `Any` still has a *static* type,
        // and losing it breaks any consumer that dispatches on the
        // destination's type rather than its contents.
        //
        // `encoding/asn1`'s `parseField` is exactly that consumer: it
        // reads `fieldType := v.Type()` and recognises an ASN.1 ANY by
        // `fieldType.Kind() == Interface`. Go's `reflect.Value` carries
        // the field's static type even when the interface it holds is
        // nil, so Go's ANY arm fires on an empty destination; returning
        // a bare `Value::Invalid` here meant goish's never did, and
        // `asn1.Unmarshal` into any struct reaching a `pkix.AttributeTypeAndValue`
        // — i.e. every X.509 Name, so every CRL — failed with
        // "unknown Go type: invalid".
        //
        // `Named` is how goish spells "this value has a declared type";
        // wrapping `Invalid` keeps the contents empty while restoring
        // the type, which is precisely Go's nil-interface Value.
        return Value::Named {
            ty: <crate::goany::Any as Reflect>::__reflect_type(),
            inner: alloc::boxed::Box::new(Value::Invalid),
        };
    }
}

// `interface{}` reflection — AnyReflect carrier. Mirrors the
// `Arc<dyn Any + Send + Sync>` flavour above, but the supertrait
// already provides per-value Reflect dispatch, so `__reflect_value`
// just delegates. This means `reflect::ValueOf(&subject)` on a
// `&Arc<dyn AnyReflect + Send + Sync>` returns the value's actual
// Kind (Struct, Slice, Map, …) instead of collapsing to the static
// downcast table — matching Go's `reflect.ValueOf(x)` semantic
// where `x` is `interface{}` carrying a real concrete type.
impl Reflect for alloc::sync::Arc<dyn AnyReflect + Send + Sync> {
    #[inline]
    fn __reflect_type() -> Type {
        Type::__new(Kind::Interface, "interface{}", &[])
    }
    #[inline]
    fn __reflect_value(&self) -> Value {
        (**self).reflect_value()
    }
}

// ─── slice<T: Reflect> — generic Reflect impl ─────────────────────────
//
// The Type descriptor itself doesn't carry the element kind in v1
// (kept off Type to avoid generic-static issues). The element's `Type`
// is reachable via the Slice variant's `elem_type` fn pointer.

impl<T: Reflect + Clone> Reflect for slice<T> {
    fn __reflect_type() -> Type {
        Type::__new(Kind::Slice, "", &[]).__with_elem(<T as Reflect>::__reflect_type)
    }
    fn __reflect_value(&self) -> Value {
        let mut items: Vec<Value> = Vec::with_capacity(self.Len() as usize);
        for i in 0..self.Len() {
            items.push((self[i]).__reflect_value());
        }
        Value::Slice {
            elem_type: <T as Reflect>::__reflect_type,
            items,
        }
    }
}

// ─── Option<T> — Go `*T` optionality ─────────────────────────────────
//
// Goish models Go's nilable pointer fields as `Option<T>` (and the
// `nilable<T>` wrapper on top of it). Reflect maps this to
// Kind::Pointer with the established nil encoding:
// `Value::Pointer(box Value::Invalid)` (the same shape `IsNil` above
// already recognizes).

impl<T: Reflect> Reflect for Option<T> {
    fn __reflect_type() -> Type {
        Type::__new(Kind::Pointer, "", &[]).__with_elem(<T as Reflect>::__reflect_type)
    }
    fn __reflect_value(&self) -> Value {
        match self {
            Some(v) => Value::Pointer(alloc::boxed::Box::new(v.__reflect_value())),
            None => Value::Pointer(alloc::boxed::Box::new(Value::Invalid)),
        }
    }
}

impl<T: FromReflectValue> FromReflectValue for Option<T> {
    fn from_reflect_value(v: Value) -> (Self, crate::error) {
        match v {
            Value::Invalid => (None, crate::errors::nil),
            Value::Pointer(inner) => match *inner {
                Value::Invalid => (None, crate::errors::nil),
                other => {
                    let (val, err) = T::from_reflect_value(other);
                    if err != crate::errors::nil {
                        (None, err)
                    } else {
                        (Some(val), crate::errors::nil)
                    }
                }
            },
            other => {
                let (val, err) = T::from_reflect_value(other);
                if err != crate::errors::nil {
                    (None, err)
                } else {
                    (Some(val), crate::errors::nil)
                }
            }
        }
    }
}

// `nilable<T>` — same Go-*T mapping as Option<T> above (nilable is
// Option<Arc<T>>-backed; reflect sees through the Arc).

impl<T: Reflect> Reflect for crate::gonilable::nilable<T> {
    fn __reflect_type() -> Type {
        Type::__new(Kind::Pointer, "", &[]).__with_elem(<T as Reflect>::__reflect_type)
    }
    fn __reflect_value(&self) -> Value {
        if self.IsNil() {
            Value::Pointer(alloc::boxed::Box::new(Value::Invalid))
        } else {
            Value::Pointer(alloc::boxed::Box::new(self.Must().__reflect_value()))
        }
    }
}

impl<T: FromReflectValue> FromReflectValue for crate::gonilable::nilable<T> {
    fn from_reflect_value(v: Value) -> (Self, crate::error) {
        let (opt, err) = <Option<T> as FromReflectValue>::from_reflect_value(v);
        if err != crate::errors::nil {
            return (crate::gonilable::nilable::default(), err);
        }
        match opt {
            Some(val) => (crate::gonilable::nilable::new(val), crate::errors::nil),
            None => (crate::gonilable::nilable::default(), crate::errors::nil),
        }
    }
}

// ─── map<K, V: Reflect> — generic Reflect impl ────────────────────────
//
// Goish's map<K,V> is BTreeMap-backed, so __iter() walks keys in sorted
// order. We preserve that order in the Map variant, which means
// json.Marshal output is deterministic for free.

use crate::gomap::map as gomap_map;

impl<K, V> Reflect for gomap_map<K, V>
where
    K: Reflect + crate::gomap::GoHash + PartialEq + Default + Clone,
    V: Reflect + Default + Clone,
{
    fn __reflect_type() -> Type {
        Type::__new(Kind::Map, "", &[])
            .__with_key(<K as Reflect>::__reflect_type)
            .__with_elem(<V as Reflect>::__reflect_type)
    }
    fn __reflect_value(&self) -> Value {
        let mut entries: Vec<(Value, Value)> = Vec::with_capacity(self.Len() as usize);
        for (k, v) in self.__iter() {
            entries.push((k.__reflect_value(), v.__reflect_value()));
        }
        Value::Map {
            key_type: <K as Reflect>::__reflect_type,
            value_type: <V as Reflect>::__reflect_type,
            entries,
        }
    }
}
